### ISSUE TITLE
Compatible with Python 3.11?

### ISSUE THREAD

**Issue by thebruge** [jaroslawhartman/withings-sync#100]
Have a new MacBook and did a fresh install of latest python, I got the authentication to Withings done, but when I run the script I get the following errors:

`2023-01-28 14:33:03,730 - root - DEBUG - 2023-01-26 07:45:21 Detected data:
2023-01-28 14:33:03,730 - root - DEBUG - Weight: 76.971 kg
2023-01-28 14:33:03,730 - root - DEBUG - Fat Mass Weight: 16.69 kg
2023-01-28 14:33:03,730 - root - DEBUG - Muscle Mass: 57.27 kg
2023-01-28 14:33:03,730 - root - DEBUG - Hydration: 42.0 kg
2023-01-28 14:33:03,730 - root - DEBUG - Bone Mass: 3.0 kg
2023-01-28 14:33:03,730 - root - DEBUG - Fat Ratio: 21.683 %
2023-01-28 14:33:03,730 - root - DEBUG - Fat Free Mass: 60.281 kg
2023-01-28 14:33:03,730 - root - DEBUG - Record: 2023-01-26 07:45:21, height=1.73 m, weight=76.97 kg, fat_ratio=21.68 %, muscle_mass=57.27 kg, percent_hydration=54.57 %, bone_mass=3.0 kg, bmi=25.7
2023-01-28 14:33:03,730 - root - DEBUG - Processed data:
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==3.5.1', 'console_scripts', 'withings-sync')())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'date_time'
Arguments: (datetime.datetime(2023, 1, 27, 8, 29, 7),)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting`

I've attached the full logs from one run. Thanks. 
[withings-sync.log](https://github.com/jaroslawhartman/withings-sync/files/10528130/withings-sync.log)

**Comment by longstone** [comment]
I saw a blood pressure measurement in the logs. May be it's related to related to #86  and #98 ?
