### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by romain-charpie** [jaroslawhartman/withings-sync#102]
From an on premise installation and also from the official docker we cannot get a sync. Everytime we get an error 503.
Below is the example from the docker:

docker run -v $HOME=/root --interactive --tty --name withings ghcr.io/jaroslawhartman/withings-sync:master --garmin-username='xxxxx' --garmin-password='yyyyyy'
2023-02-07 09:37:13,104 - withings - ERROR - Can't read config file /root/.withings_user.json
2023-02-07 09:37:13,104 - withings - WARNING - User interaction needed to get Authentification Code from Withings!
2023-02-07 09:37:13,105 - withings - WARNING -
2023-02-07 09:37:13,105 - withings - WARNING - Open the following URL in your web browser and copy back the token. You will have *30 seconds* before the token expires. HURRY UP!
2023-02-07 09:37:13,105 - withings - WARNING - (This is one-time activity)
2023-02-07 09:37:13,105 - withings - WARNING -
2023-02-07 09:37:13,105 - withings - INFO - https://account.withings.com/oauth2_user/authorize2?response_type=code&client_id=183e03e1f363110b3551f96765c98c10e8f1aa647a37067a1cb64bbbaf491626&state=OK&scope=user.metrics&redirect_uri=https://jaroslawhartman.github.io/withings-sync/contrib/withings.html&
2023-02-07 09:37:13,105 - withings - INFO -
Token : VVVVVVV
2023-02-07 09:37:45,591 - withings - INFO - Get Access Token
2023-02-07 09:37:45,881 - withings - ERROR - Received error code: 503
2023-02-07 09:37:45,881 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2023-02-07 09:37:45,881 - withings - ERROR -
2023-02-07 09:37:45,882 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
2023-02-07 09:37:45,882 - withings - INFO - Refresh Access Token
2023-02-07 09:37:46,100 - withings - ERROR - Received error code: 503
2023-02-07 09:37:46,100 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2023-02-07 09:37:46,100 - withings - ERROR -
2023-02-07 09:37:46,100 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==3.5.1', 'console_scripts', 'withings-sync')())
  File "/usr/local/lib/python3.10/site-packages/withings_sync-3.5.1-py3.10.egg/withings_sync/sync.py", line 401, in main
    sync()
  File "/usr/local/lib/python3.10/site-packages/withings_sync-3.5.1-py3.10.egg/withings_sync/sync.py", line 328, in sync
    withings = WithingsAccount()
  File "/usr/local/lib/python3.10/site-packages/withings_sync-3.5.1-py3.10.egg/withings_sync/withings2.py", line 189, in __init__
    self.withings = WithingsOAuth2()
  File "/usr/local/lib/python3.10/site-packages/withings_sync-3.5.1-py3.10.egg/withings_sync/withings2.py", line 73, in __init__
    self.refresh_accesstoken()
  File "/usr/local/lib/python3.10/site-packages/withings_sync-3.5.1-py3.10.egg/withings_sync/withings2.py", line 180, in refresh_accesstoken
    self.user_config["access_token"] = body.get("access_token")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by szpeti40** [comment]
I also get 503 error since yesterday:

```
2023-02-18 20:05:02,231 - withings - INFO - Refresh Access Token
2023-02-18 20:05:02,505 - withings - ERROR - Received error code: 503
2023-02-18 20:05:02,505 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2023-02-18 20:05:02,505 - withings - ERROR -
2023-02-18 20:05:02,505 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
2023-02-18 20:05:02,508 - root - INFO - Fetching measurements from 2023-02-11 19:05 to 2023-02-18 22:59
2023-02-18 20:05:02,746 - withings - INFO - Get Measurements
2023-02-18 20:05:02,960 - root - ERROR - No measurements to upload for date or period specified
```


How can I get a new withings token link where the script worked fine?

**Comment by romain-charpie** [comment]
Hello,

I just tested again today and still get the same issue.
Impossible to validate the token. Error 503 either from docker or a Linux VM.

Did anyone have the same issue?

**Comment by szpeti40** [comment]
> Hello,
> 
> I just tested again today and still get the same issue. Impossible to validate the token. Error 503 either from docker or a Linux VM.
> 
> Did anyone have the same issue?

Hello!

I had a same issue.
I deleted the /root/.withings_user.json file and rerun the script. It has been working fine since then.

**Comment by longstone** [comment]
Found the same issue, in my case

```
cat .withings_user.json 
{
    "access_token": null,
    "authentification_code": "value",
    "last_sync": value,
    "refresh_token": null,
    "userid": null
}l
```

so it seems to have a update issue...

**Comment by longstone** [comment]
> I deleted the /root/.withings_user.json file and rerun the script. It has been working fine since then.

this resolves the issue
