### ISSUE TITLE
 Max retries exceeded with url: /oauth2/token 

### ISSUE THREAD

**Issue by MSMortensen** [jaroslawhartman/withings-sync#11]
Hi,

I used the docker implementation and that ran a cornjob to sync hourly.
After 5 days it stopped working with the error message below.
I tried removing the docker container and set it up again from scratch, but got the same error message.

Any suggestion how I can get it to run?

(I set it up using cli on my NAS (Linux AS6302T 4.14.x #1 SMP Fri Oct 16 00:30:37 CST 2020 x86_64 GNU/Linux)

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5447a84040>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account.withings.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5447a84040>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==3.1.2', 'console_scripts', 'withings-sync')())
  File "/usr/local/lib/python3.8/site-packages/withings_sync-3.1.2-py3.8.egg/withings_sync/sync.py", line 191, in main
    sync(**vars(args))
  File "/usr/local/lib/python3.8/site-packages/withings_sync-3.1.2-py3.8.egg/withings_sync/sync.py", line 77, in sync
    withings = WithingsAccount()
  File "/usr/local/lib/python3.8/site-packages/withings_sync-3.1.2-py3.8.egg/withings_sync/withings2.py", line 161, in __init__
    self.withings = WithingsOAuth2()
  File "/usr/local/lib/python3.8/site-packages/withings_sync-3.1.2-py3.8.egg/withings_sync/withings2.py", line 61, in __init__
    self.refreshAccessToken()
  File "/usr/local/lib/python3.8/site-packages/withings_sync-3.1.2-py3.8.egg/withings_sync/withings2.py", line 137, in refreshAccessToken
    req = requests.post(Withings.TOKEN_URL, params)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='account.withings.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5447a84040>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by jaroslawhartman** [comment]
Hi @MSMortensen 

I think this is pretty much expected that there will be a limit. I'm not sure what's the max and how requests are counted (is it per user or the max is shared for whole app).

I'd suggest to decrease frequency, I believe the counter will get reset-ed after a while. Personally I run the sync once a day.

Best regards,
Jarek

**Comment by MSMortensen** [comment]
Thanks for the quick reply.
I will disable it and try and see if it will run tomorrow.

If I set it to sync daily is there a way to ensure that I do not miss any measurements without hardcoding a --fromdate? 
For example always make it sync any measurements from yesterday and today?

Best regards,
Martin

**Comment by jaroslawhartman** [comment]
Hi,

I start the script daily in the afternoon without any date parameters. If you're afraid of loosing measurements, you could schedule it just before midnight.

Best regards

**Comment by MSMortensen** [comment]
Hi again,
I removed the docker container and image, as well as .withings_user.json, and tried to install it again.

I get the same error as before.
Any idea how I can get it to work again?

Best Martin

PS: I used my garmin username and password

$ docker run -v $HOME:/root --interactive --tty --name withings stv0g/withings-sync --garmin-username={MY_USERNAME} --garmin-password={MY_PASSWORD}
Unable to find image 'stv0g/withings-sync:latest' locally
latest: Pulling from stv0g/withings-sync
df20fa9351a1: Pull complete
36b3adc4ff6f: Pull complete
3e7ef1bb9eba: Pull complete
78538f72d6a9: Pull complete
1692f1a2776b: Pull complete
4dacf6c2b0b3: Pull complete
c860f9f6deb6: Pull complete
49e18d18e796: Pull complete
5ef3985ee8a9: Pull complete
ae195f2fe619: Pull complete
Digest: sha256:342fbae1c3cfa40c4f91bcbe555abb3038a1d9e14ab091463846671d1de874b4
Status: Downloaded newer image for stv0g/withings-sync:latest
2020-11-08 13:30:33,043 - withings - ERROR - Can't read config file /root/.withings_user.json
2020-11-08 13:30:33,044 - withings - WARNING - User interaction needed to get Authentification Code from Withings!
2020-11-08 13:30:33,044 - withings - WARNING -
2020-11-08 13:30:33,044 - withings - WARNING - Open the following URL in your web browser and copy back the token. You will have *30 seconds* before the token expires. HURRY UP!
2020-11-08 13:30:33,045 - withings - WARNING - (This is one-time activity)
2020-11-08 13:30:33,045 - withings - WARNING -
2020-11-08 13:30:33,045 - withings - INFO - https://account.withings.com/oauth2_user/authorize2?response_type=code&client_id=183e03e1f363110b3551f96765c98c10e8f1aa647a37067a1cb64bbbaf491626&state=OK&scope=user.metrics&redirect_uri=https://jaroslawhartman.github.io/withings-sync/contrib/withings.html&
2020-11-08 13:30:33,046 - withings - INFO -
Token : 1fe12aff58bb01943b4750fd7e2fd2cda11de1f1
2020-11-08 13:30:53,622 - withings - INFO - Get Access Token
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe503241040>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account.withings.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe503241040>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==3.1.2', 'console_scripts', 'withings-sync')())
  File "/usr/local/lib/python3.8/site-packages/withings_sync-3.1.2-py3.8.egg/withings_sync/sync.py", line 191, in main
    sync(**vars(args))
  File "/usr/local/lib/python3.8/site-packages/withings_sync-3.1.2-py3.8.egg/withings_sync/sync.py", line 77, in sync
    withings = WithingsAccount()
  File "/usr/local/lib/python3.8/site-packages/withings_sync-3.1.2-py3.8.egg/withings_sync/withings2.py", line 161, in __init__
    self.withings = WithingsOAuth2()
  File "/usr/local/lib/python3.8/site-packages/withings_sync-3.1.2-py3.8.egg/withings_sync/withings2.py", line 59, in __init__
    self.getAccessToken()
  File "/usr/local/lib/python3.8/site-packages/withings_sync-3.1.2-py3.8.egg/withings_sync/withings2.py", line 106, in getAccessToken
    req = requests.post(Withings.TOKEN_URL, params)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='account.withings.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe503241040>: Failed to establish a new connection: [Errno -3] Try again'))
