### ISSUE TITLE
AttributeError: 'SSLContext' object has no attribute 'orig_wrap_socket'

### ISSUE THREAD

**Issue by arutscheidt** [jaroslawhartman/withings-sync#111]
Hello,
my script starts a normal run with garmin

withings-sync --gu 'xxx' --gp xxx' -J -o Gewicht_${nextDate} -f ${nextDate}
But I get the following error.

Any hints?

`
 ./sync.sh

2023-03-24 23:45:23,547 - withings - INFO - Refresh Access Token
2023-03-24 23:45:23,715 - root - INFO - Fetching measurements from 2022-09-03 22:00 to 2023-03-24 22:59
2023-03-24 23:45:23,899 - withings - INFO - Get Measurements
2023-03-24 23:45:24,323 - root - INFO - Writing jsonfile to Gewicht_2022-09-04.json.
2023-03-24 23:45:24,340 - root - INFO - No Trainerroad username or a new measurement - skipping sync
Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/usr/local/lib/python3.6/dist-packages/withings_sync/sync.py", line 366, in sync
    if sync_garmin(fit_data):
  File "/usr/local/lib/python3.6/dist-packages/withings_sync/sync.py", line 137, in sync_garmin
    session = garmin.login(ARGS.garmin_username, ARGS.garmin_password)
  File "/usr/local/lib/python3.6/dist-packages/withings_sync/garmin.py", line 183, in login
    session = GarminConnect.get_session(email=username, password=password)
  File "/usr/local/lib/python3.6/dist-packages/withings_sync/garmin.py", line 55, in get_session
    session = cloudscraper.CloudScraper()
  File "/usr/local/lib/python3.6/dist-packages/cloudscraper/__init__.py", line 171, in __init__
    ssl_context=self.ssl_context
  File "/usr/local/lib/python3.6/dist-packages/cloudscraper/__init__.py", line 77, in __init__
    self.ssl_context.orig_wrap_socket = self.ssl_context.wrap_socket
AttributeError: 'SSLContext' object has no attribute 'orig_wrap_socket'
`

Best regards

**Comment by arutscheidt** [comment]
Found my solution in this [answer](https://stackoverflow.com/questions/71548899/cloudscraper-returns-attributeerror-sslcontext-object-has-no-attribute-orig) by downgrading my cloudscraper for the moment.
If I have time I will backup and update the whole system and get a newer version of python.
