### ISSUE TITLE
RuntimeError posting to Trainerroad

### ISSUE THREAD

**Issue by jmclaughlin-tssg** [jaroslawhartman/withings-sync#118]
Running version 3.6.1

When posting to Trainerroad, a runtime error occurs when posting an update:

```
2023-05-13 12:47:36,364 - urllib3.connectionpool - DEBUG - https://www.trainerroad.com:443 "GET /app/logout HTTP/1.1" 302 144
2023-05-13 12:47:36,371 - withings_sync.trainerroad - INFO - Logged out of TrainerRoad as "xxxxx@xxxx.xxx"
Traceback (most recent call last):
  File "/home/mclaughj/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/mclaughj/.local/lib/python3.8/site-packages/withings_sync/sync.py", line 496, in main
    sync()
  File "/home/mclaughj/.local/lib/python3.8/site-packages/withings_sync/sync.py", line 456, in sync
    if sync_trainerroad(last_weight):
  File "/home/mclaughj/.local/lib/python3.8/site-packages/withings_sync/sync.py", line 174, in sync_trainerroad
    return t_road.weight
  File "/home/mclaughj/.local/lib/python3.8/site-packages/withings_sync/trainerroad.py", line 175, in weight
    values, token = self._read_profile()
  File "/home/mclaughj/.local/lib/python3.8/site-packages/withings_sync/trainerroad.py", line 105, in _read_profile
    r = self._get(self._rider_url)
  File "/home/mclaughj/.local/lib/python3.8/site-packages/withings_sync/trainerroad.py", line 82, in _get
    raise RuntimeError('Not Connected')
RuntimeError: Not Connected
```
This means that posting to Garmin in the same run also fails.

`t_road.weight` calls `_read_profile` on a closed connection - hence the error

Refactoring to the following seems to fix the issue

```diff
*** withings_sync/sync.py       2023-05-13 12:40:35.171480882 +0100
--- withings_sync.orig/sync.py  2023-05-01 18:22:14.971165895 +0100
***************
*** 169,178 ****
      t_road.connect()
      logging.info("Current TrainerRoad weight: %s kg ", t_road.weight)
      logging.info("Updating TrainerRoad weight to %s kg", last_weight)
!     wt = round(last_weight, 1)
!     t_road.weight = wt
      t_road.disconnect()
!     return wt
  
  
  def generate_fitdata(syncdata):
--- 169,177 ----
      t_road.connect()
      logging.info("Current TrainerRoad weight: %s kg ", t_road.weight)
      logging.info("Updating TrainerRoad weight to %s kg", last_weight)
!     t_road.weight = round(last_weight, 1)
      t_road.disconnect()
!     return t_road.weight
```

**Comment by longstone** [comment]
Please create a PR. 
As an idea we could wrap it in a try catch block and wrap t_road.disconnect() in a finally?

**Comment by jaroslawhartman** [comment]
Should be fixed in f325d8c .
Will be published at next opportunity by @longstone
