### ISSUE TITLE
withings connction error 

### ISSUE THREAD

**Issue by hokrai** [jaroslawhartman/withings-sync#121]
Hello 

I've try to connect to withings with token and impossible after many retries 10s or 20s ... the same error 503 ..

> withings-sync --fromdate 2010-01-01 --to-fit --output toto --no-upload --verbose
2023-07-18 10:55:07,631 - root - DEBUG - Script invoked with the following arguments: Namespace(garmin_username='', garmin_password='', trainerroad_username='', trainerroad_password='', fromdate=datetime.datetime(2010, 1, 1, 0, 0), todate=datetime.date(2023, 7, 18), to_fit=True, to_json=False, output='toto', no_upload=True, features=[], verbose=True)
2023-07-18 10:55:07,632 - withings - ERROR - Can't read config file /Users/xxxx/.withings_user.json
2023-07-18 10:55:07,632 - withings - WARNING - User interaction needed to get Authentification Code from Withings!
2023-07-18 10:55:07,632 - withings - WARNING - 
2023-07-18 10:55:07,632 - withings - WARNING - Open the following URL in your web browser and copy back the token. You will have *30 seconds* before the token expires. HURRY UP!
2023-07-18 10:55:07,632 - withings - WARNING - (This is one-time activity)
2023-07-18 10:55:07,632 - withings - WARNING - 
2023-07-18 10:55:07,632 - withings - INFO - https://account.withings.com/oauth2_user/authorize2?response_type=code&client_id=xxxxxxxxxxxxxx&state=OK&scope=user.metrics&redirect_uri=https://jaroslawhartman.github.io/withings-sync/contrib/withings.html&
2023-07-18 10:55:07,632 - withings - INFO - 
Token : 97337201
2023-07-18 10:55:38,388 - withings - INFO - Get Access Token
2023-07-18 10:55:38,400 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2023-07-18 10:55:38,549 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /v2/oauth2 HTTP/1.1" 200 63
2023-07-18 10:55:38,550 - withings - ERROR - Received error code: 503
2023-07-18 10:55:38,550 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2023-07-18 10:55:38,550 - withings - ERROR - 
2023-07-18 10:55:38,550 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
2023-07-18 10:55:38,551 - withings - INFO - Refresh Access Token
2023-07-18 10:55:38,554 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2023-07-18 10:55:38,635 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /v2/oauth2 HTTP/1.1" 200 64
2023-07-18 10:55:38,635 - withings - ERROR - Received error code: 503
2023-07-18 10:55:38,636 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2023-07-18 10:55:38,636 - withings - ERROR - 
2023-07-18 10:55:38,636 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/withings_sync/sync.py", line 496, in main
    sync()
  File "/usr/local/lib/python3.11/site-packages/withings_sync/sync.py", line 415, in sync
    withings = WithingsAccount()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/withings_sync/withings2.py", line 189, in __init__
    self.withings = WithingsOAuth2()
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/withings_sync/withings2.py", line 73, in __init__
    self.refresh_accesstoken()
  File "/usr/local/lib/python3.11/site-packages/withings_sync/withings2.py", line 180, in refresh_accesstoken
    self.user_config["access_token"] = body.get("access_token")
                                       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Hazy87** [comment]
I think there is something wrong with the developers withings developer account. I fixed mine by looking at the "For advanced users - registering own Withings application" section in the readme. I didnt bother to create my own url I just used say https://www.google.com   and pulled the token out of the url bar when setting up for the first time.
Hope this helps.

**Comment by hokrai** [comment]
Thanks ...
It's ok after creating an app on dev wihting portal with callback url ...
But sync only weight and not activities ...

**Comment by stynoo** [comment]
This is expected.  The script 'only' syncs body stats, no activities.

**Comment by marlemion** [comment]
The proposed solution is not working with docker, as withing_app.json has to be modified. The developer should fix the account imho.

**Comment by Olen** [comment]
Made a PR that describes how this can be solved in a Docker container:
#122 

Also included a fix that will retry with a new auth_code if login fails

**Comment by longstone** [comment]
The PR was merged, no activity. Closing this one.
