### ISSUE TITLE
Errors while running withings-sync -f 2023-10-13 -v

### ISSUE THREAD

**Issue by jfgarciamex** [jaroslawhartman/withings-sync#149]
Hi, I been using withings-sync for a while now, but just a few weeks noticed that is no longer updating information in garming connect. So after updating to the latest version, and updating raspberry os to the latest too, I keep getting the same errors. Any suggestion is appreciated!

While running the following command:

`withings-sync -f 2023-10-13 -v`

The logging I see is as follows (masking garmin user and password):
```
2023-10-14 10:17:49,678 - root - DEBUG - Script invoked with the following arguments: Namespace(garmin_username='xxx@yyy', garmin_password='zzz', trainerroad_username='', trainerroad_password='', fromdate=datetime.datetime(2023, 10, 13, 0, 0), todate=datetime.date(2023, 10, 14), to_fit=False, to_json=False, output=None, no_upload=False, verbose=True)
2023-10-14 10:17:49,680 - withings - INFO - Refresh Access Token
2023-10-14 10:17:49,691 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2023-10-14 10:17:50,976 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /v2/oauth2 HTTP/1.1" 200 220
2023-10-14 10:17:50,992 - root - INFO - Fetching measurements from 2023-10-13 06:00 to 2023-10-15 05:59
2023-10-14 10:17:50,992 - withings - DEBUG - Get Height
2023-10-14 10:17:50,997 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2023-10-14 10:17:51,925 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /measure?action=getmeas HTTP/1.1" 200 346
2023-10-14 10:17:51,932 - withings - DEBUG - Height received
2023-10-14 10:17:51,933 - withings - INFO - Get Measurements
2023-10-14 10:17:51,940 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2023-10-14 10:17:52,931 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /measure?action=getmeas HTTP/1.1" 200 703
2023-10-14 10:17:52,937 - withings - DEBUG - Measurements received
2023-10-14 10:17:52,938 - root - DEBUG - 2023-10-13 06:35:19 Detected data:
2023-10-14 10:17:52,939 - root - DEBUG - Weight: 82.73 kg
2023-10-14 10:17:52,939 - root - DEBUG - Fat Mass Weight: 23.400000000000002 kg
2023-10-14 10:17:52,940 - root - DEBUG - Muscle Mass: 56.31 kg
2023-10-14 10:17:52,940 - root - DEBUG - Hydration: 40.62 kg
2023-10-14 10:17:52,941 - root - DEBUG - Bone Mass: 3.0 kg
2023-10-14 10:17:52,941 - root - DEBUG - Fat Ratio: 28.285 %
2023-10-14 10:17:52,941 - root - DEBUG - Fat Free Mass: 59.33 kg
2023-10-14 10:17:52,942 - root - DEBUG - Record: 2023-10-13 06:35:19, height=1.8 m, weight=82.73 kg, fat_ratio=28.29 %, muscle_mass=56.31 kg, percent_hydration=49.1 %, bone_mass=3.0 kg, bmi=25.5
2023-10-14 10:17:52,943 - root - DEBUG - Processed data:
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'date_time'
Arguments: (datetime.datetime(2023, 10, 13, 6, 35, 19),)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'height'
Arguments: (1.8,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'weight'
Arguments: (82.73,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'fat_ratio'
Arguments: (28.29,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'muscle_mass'
Arguments: (56.31,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'hydration'
Arguments: (40.62,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'percent_hydration'
Arguments: (49.1,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'bone_mass'
Arguments: (3.0,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'pulse_wave_velocity'
Arguments: (None,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'heart_pulse'
Arguments: (None,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'bmi'
Arguments: (25.5,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/withings-sync/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/home/withings-sync/.local/lib/python3.9/site-packages/withings_sync/sync.py", line 286, in prepare_syncdata
    logging.debug(k, v)
Message: 'raw_data'
Arguments: ([<withings_sync.withings2.WithingsMeasure object at 0x7f86173ca0>, <withings_sync.withings2.WithingsMeasure object at 0x7f86173be0>, <withings_sync.withings2.WithingsMeasure object at 0x7f861737c0>, <withings_sync.withings2.WithingsMeasure object at 0x7f86173880>, <withings_sync.withings2.WithingsMeasure object at 0x7f86173a60>, <withings_sync.withings2.WithingsMeasure object at 0x7f861829a0>, <withings_sync.withings2.WithingsMeasure object at 0x7f86182850>],)
2023-10-14 10:17:53,054 - root - DEBUG - last_dt: 2023-10-13 06:35:19 last_weight: 82.73
2023-10-14 10:17:53,055 - root - DEBUG - Generating fit data...
2023-10-14 10:17:53,058 - root - DEBUG - Fit data generated...
2023-10-14 10:17:53,059 - root - DEBUG - Generating json data...
2023-10-14 10:17:53,060 - root - DEBUG - Json data generated...
2023-10-14 10:17:53,061 - root - INFO - No Trainerroad username or a new measurement - skipping sync
2023-10-14 10:17:53,063 - root - DEBUG - attempting to upload fit file...
2023-10-14 10:17:53,099 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): sso.garmin.com:443
2023-10-14 10:17:53,475 - urllib3.connectionpool - DEBUG - https://sso.garmin.com:443 "GET /sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&clientId=GarminConnect&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&consumeServiceTicket=false HTTP/1.1" 200 None
2023-10-14 10:17:54,281 - urllib3.connectionpool - DEBUG - https://sso.garmin.com:443 "POST /sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&clientId=GarminConnect&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&consumeServiceTicket=false HTTP/1.1" 200 None
2023-10-14 10:17:54,299 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): connect.garmin.com:443
2023-10-14 10:17:54,657 - urllib3.connectionpool - DEBUG - https://connect.garmin.com:443 "GET /modern HTTP/1.1" 302 0
2023-10-14 10:17:54,847 - urllib3.connectionpool - DEBUG - https://sso.garmin.com:443 "GET /sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&webhost=https%3A%2F%2Fconnect.garmin.com&gateway=true&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=true&clientId=GarminConnect HTTP/1.1" 302 0
2023-10-14 10:17:54,961 - urllib3.connectionpool - DEBUG - https://connect.garmin.com:443 "GET /modern/ HTTP/1.1" 302 0
2023-10-14 10:17:55,046 - urllib3.connectionpool - DEBUG - https://connect.garmin.com:443 "GET /signin/?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F HTTP/1.1" 200 None
2023-10-14 10:17:55,052 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): connect.garmin.com:80
2023-10-14 10:17:55,177 - urllib3.connectionpool - DEBUG - http://connect.garmin.com:80 "GET /modern HTTP/1.1" 301 None
2023-10-14 10:17:55,253 - urllib3.connectionpool - DEBUG - https://connect.garmin.com:443 "GET /modern HTTP/1.1" 302 0
2023-10-14 10:17:55,335 - urllib3.connectionpool - DEBUG - https://connect.garmin.com:443 "GET /signin/?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F HTTP/1.1" 200 None
2023-10-14 10:17:55,339 - garmin - ERROR - 'NoneType' object is not subscriptable
2023-10-14 10:17:55,339 - garmin - ERROR - Unable to retrieve Garmin username! Most likely: incorrect Garmin login or password!
2023-10-14 10:17:55,339 - garmin - DEBUG - <!DOCTYPE html><html><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><style data-href="/styles.a8465107f99a824f09fa.css" id="gatsby-global-css">body,html{height:auto;font:400 14px/22px Open Sans,Helvetica Neue,Helvetica,Arial,sans-serif;color:#222;background-color:#efefef;margin:0}a,a:active,a:hover,a:visited{text-decoration:none;color:inherit}#truste-consent-track{display:block}#truste-consent-content{display:flex;align-items:center;justify-content:center;flex-wrap:wrap;width:100%;box-sizing:border-box}#truste-consent-text{margin:0 1rem 0 0;color:#fff;font-size:16px;font-weight:700;font-family:arial}#truste-consent-buttons>a{color:#fff;font-size:14px;margin:12px 10px 10px;text-align:center;text-decoration:underline}#truste-consent-buttons{display:flex;flex-direction:row;margin-top:1px!important;margin-left:10px!important}#truste-consent-buttons #truste-consent-button,#truste-consent-buttons #truste-consent-required,#truste-consent-buttons #truste-show-consent{font-family:Open Sans,HelveticaNeue,HelveticaNeueu,Arial,sans-serif;font-size:14px;color:#fff;background-color:#4a4a4a;cursor:pointer;padding:5px 20px;margin:12px 0;border-radius:4px;border:none}#truste-consent-buttons #truste-consent-required{margin-left:.5rem}#truste-consent-buttons #truste-show-consent{margin-left:1rem}#truste-consent-buttons #truste-consent-button:hover,#truste-consent-buttons #truste-consent-required:hover,#truste-consent-buttons #truste-show-consent:hover{background-color:#242424;border:none}#truste-cookie-button{color:#fff;margin:1rem;line-height:2}@media (max-width:1024px){#truste-consent-content{flex-direction:column;flex-wrap:nowrap}#truste-consent-text{margin:20px 20px 10px;text-align:center;width:unset!important}#truste-consent-buttons{display:block;text-align:center}#truste-consent-buttons #truste-consent-button,#truste-consent-buttons #truste-consent-required,#truste-consent-buttons #truste-show-consent{padding-top:10px;padding-bottom:10px;width:100%;margin:5px 0}#truste-cookie-button{display:inline-block;margin:auto;padding:15px}#truste-consent-buttons #truste-show-consent{margin-left:0}}.truste_overlay{background:#fff!important;opacity:.8!important}.truste_box_overlay{background:none!important}.truste_box_overlay_inner{border:3px solid #e8e8e8}</style><meta name="generator" content="Gatsby 2.32.13"/><title data-react-helmet="true"></title><style type="text/css" id="server-side-jss"></style><link as="script" rel="preload" href="/webpack-runtime-a98152bc3e9e1f034dfd.js"/><link as="script" rel="preload" href="/framework-f3ec01444cccc4b4057e.js"/><link as="script" rel="preload" href="/styles-2ed6c2e7b748a8320e46.js"/><link as="script" rel="preload" href="/app-949317601b74f8af13e9.js"/><link as="script" rel="preload" href="/eaeed06d504ae546165ee91c3dc1e07947955f13-6dcd5ab7da14191eae89.js"/><link as="script" rel="preload" href="/component---src-pages-signin-js-be26445497aefe4010f7.js"/><link as="fetch" rel="preload" href="/page-data/signin/page-data.json" crossorigin="anonymous"/><link as="fetch" rel="preload" href="/page-data/app-data.json" crossorigin="anonymous"/></head><body><div id="___gatsby"><div style="outline:none" tabindex="-1" id="gatsby-focus-wrapper"><noscript>To sign in to your Garmin account, please enable JavaScript in your web browser.</noscript></div><div id="gatsby-announcer" style="position:absolute;top:0;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0, 0, 0, 0);white-space:nowrap;border:0" aria-live="assertive" aria-atomic="true"></div></div><script id="gatsby-script-loader">/*<![CDATA[*/window.pagePath="/signin/";/*]]>*/</script><script id="gatsby-chunk-mapping">/*<![CDATA[*/window.___chunkMapping={"polyfill":["/polyfill-9a6e2095c8f8c9aa1c78.js"],"app":["/app-949317601b74f8af13e9.js"],"component---src-pages-404-js":["/component---src-pages-404-js-774b69b42bb6abedb791.js"],"component---src-pages-account-sharing-js":["/component---src-pages-account-sharing-js-989eff6a0cc060a09afd.js"],"component---src-pages-create-account-js":["/component---src-pages-create-account-js-4a3549073a62d1464afe.js"],"component---src-pages-features-coach-js":["/component---src-pages-features-coach-js-d9321bc482001e74c4e0.js"],"component---src-pages-features-index-js":["/component---src-pages-features-index-js-990a38d4b41e39285884.js"],"component---src-pages-features-menstrual-cycle-tracking-js":["/component---src-pages-features-menstrual-cycle-tracking-js-139b248782082c21d24f.js"],"component---src-pages-features-pregnancy-tracking-js":["/component---src-pages-features-pregnancy-tracking-js-5cc46b4183e753526536.js"],"component---src-pages-index-js":["/component---src-pages-index-js-848563019fe90b815f1a.js"],"component---src-pages-invite-signin-js":["/component---src-pages-invite-signin-js-b683c003279536f6c2be.js"],"component---src-pages-signin-js":["/component---src-pages-signin-js-be26445497aefe4010f7.js"],"component---src-pages-start-index-js":["/component---src-pages-start-index-js-891231321782023bf4f0.js"],"component---src-pages-start-index-scale-express-js":["/component---src-pages-start-index-scale-express-js-8480cb34c912ccb8a240.js"],"component---src-pages-start-index-scale-help-js":["/component---src-pages-start-index-scale-help-js-8b4d550ac7dbb4fe81d6.js"],"component---src-pages-start-index-scale-index-js":["/component---src-pages-start-index-scale-index-js-899da91c4ee27b0d298b.js"],"component---src-pages-start-index-scale-mobile-js":["/component---src-pages-start-index-scale-mobile-js-19844f0f9bc606348cb5.js"],"component---src-pages-start-index-scale-wps-js":["/component---src-pages-start-index-scale-wps-js-e6fa9806d7cd2ed613b6.js"],"component---src-pages-start-quickdraw-js":["/component---src-pages-start-quickdraw-js-795e397fac9634ea9033.js"],"component---src-pages-start-quickdraw-legal-js":["/component---src-pages-start-quickdraw-legal-js-fc8979099ccef79743b7.js"],"component---src-pages-start-vivoki-js":["/component---src-pages-start-vivoki-js-22a13a64942f48b7e562.js"],"component---src-pages-status-js":["/component---src-pages-status-js-bb6902bb697c82eb40c7.js"],"component---src-pages-support-js":["/component---src-pages-support-js-95d4a125e624cfe6505c.js"]};/*]]>*/</script><script src="/polyfill-9a6e2095c8f8c9aa1c78.js" nomodule=""></script><script src="/component---src-pages-signin-js-be26445497aefe4010f7.js" async=""></script><script src="/eaeed06d504ae546165ee91c3dc1e07947955f13-6dcd5ab7da14191eae89.js" async=""></script><script src="/app-949317601b74f8af13e9.js" async=""></script><script src="/styles-2ed6c2e7b748a8320e46.js" async=""></script><script src="/framework-f3ec01444cccc4b4057e.js" async=""></script><script src="/webpack-runtime-a98152bc3e9e1f034dfd.js" async=""></script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854" integrity="sha512-bjgnUKX4azu3dLTVtie9u6TKqgx29RBwfj3QXYt5EKfWM/9hPSAI/4qcV5NACjwAo8UtTeWefx6Zq5PHcMm7Tg==" data-cf-beacon='{"rayId":"816122a08edb486a","version":"2023.8.0","b":1,"token":"1bd18b8f69214e379ef7bd34509191ae","si":100}' crossorigin="anonymous"></script>
</body></html>
2023-10-14 10:17:55,468 - urllib3.connectionpool - DEBUG - https://connect.garmin.com:443 "POST /modern/proxy/upload-service/upload/.fit HTTP/1.1" 403 None
2023-10-14 10:17:55,474 - garmin - ERROR - Bad response during GC upload: 403
```

**Comment by stynoo** [comment]
Can you update first to the latest version and check again?

**Comment by jfgarciamex** [comment]
Just did, and same errors...

**Comment by stynoo** [comment]
It seems that there is something wrong with your environment or something went wrong with the update/install of the script.   
The latest version should at least get rid of this garmin error at the end `garmin - ERROR - 'NoneType' object is not subscriptable`

Also, the issue you are seeing with ` logging.debug(k, v)` purely relates to debug logging,, you can try to remove the verbose argument when invoking the script.  

Another test you can do is clone the repo and work with those files, or better, run the container.

**Comment by jfgarciamex** [comment]
@stynoo Thanks!... I deleted the .local directory within the user where I have withings-sync installed (I only have withings-sync, so it was a safe move), and installed again using `pip install withings-sync` and now is working!
