### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by fir3drag0n** [jaroslawhartman/withings-sync#168]
Hi,

unfortunately, I cannot get docker so start. I have used the correct token, but I always get the same result:

`2024-04-23 09:46:10,495 - withings - INFO - Get Access Token
2024-04-23 09:46:10,671 - withings - INFO - Refresh Access Token
2024-04-23 09:46:10,828 - root - INFO - Fetching measurements from 2022-01-01 00:00 to 2024-04-23 23:59
2024-04-23 09:46:11,038 - withings - INFO - Get Measurements
2024-04-23 09:46:11,228 - root - INFO - No blood pressure data to sync for FIT file
2024-04-23 09:46:11,228 - root - INFO - No TrainerRoad username or a new measurement - skipping sync
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.45-py3.10.egg/garth/http.py", line 139, in request
    self.last_resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests-2.31.0-py3.10.egg/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.4-py3.10.egg/withings_sync/garmin.py", line 44, in login
    self.client.login(email, password)
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.45-py3.10.egg/garth/http.py", line 160, in login
    self.oauth1_token, self.oauth2_token = sso.login(
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.45-py3.10.egg/garth/sso.py", line 83, in login
    client.post(
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.45-py3.10.egg/garth/http.py", line 151, in post
    return self.request("POST", *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.45-py3.10.egg/garth/http.py", line 141, in request
    raise GarthHTTPError(
garth.exc.GarthHTTPError: Error in request: 401 Client Error: Unauthorized for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==4.2.4', 'console_scripts', 'withings-sync')())
  File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.4-py3.10.egg/withings_sync/sync.py", line 505, in main
    sync()
  File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.4-py3.10.egg/withings_sync/sync.py", line 466, in sync
    gar_wg_state = sync_garmin(fit_data_weight)
  File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.4-py3.10.egg/withings_sync/sync.py", line 157, in sync_garmin
    garmin.login(ARGS.garmin_username, ARGS.garmin_password)
  File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.4-py3.10.egg/withings_sync/garmin.py", line 47, in login
    raise APIException("Authentication failure: {}. Did you enter correct credentials?".format(ex))
withings_sync.garmin.APIException: Authentication failure: Error in request: 401 Client Error: Unauthorized for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed. Did you enter correct credentials?
`

**Comment by JeanMichelDeveloper** [comment]
Hello,

Same problem for me when I run it in Powershell. When I enter my cedentials using the SSO link I don't have any issue.

**Comment by michaelknox** [comment]
I think i might have the same problem: 


```
user@server:~$ docker start -i 35ba9edeb7a62835c5771842949b34003ad1395d6135c5c12d7d8885c56feca5
2024-10-21 12:47:33,114 - withings - INFO - Refresh Access Token
2024-10-21 12:47:33,325 - root - INFO - Fetching measurements from 2024-08-08 20:01 to 2024-10-21 23:59
2024-10-21 12:47:33,618 - withings - INFO - Get Measurements
2024-10-21 12:47:33,833 - root - INFO - 2024-10-01 07:32:57 This Withings metric contains no weight data or blood pressure.  Not syncing...
2024-10-21 12:47:33,835 - root - INFO - 2024-08-22 05:34:55 This Withings metric contains no weight data or blood pressure.  Not syncing...
2024-10-21 12:47:33,851 - root - INFO - No TrainerRoad username or a new measurement - skipping sync
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests-2.32.3-py3.10.egg/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==4.2.6a0', 'console_scripts', 'withings-sync')())
  File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.6a0-py3.10.egg/withings_sync/sync.py", line 510, in main
    sync()
  File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.6a0-py3.10.egg/withings_sync/sync.py", line 469, in sync
    gar_wg_state = sync_garmin(fit_data_weight)
  File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.6a0-py3.10.egg/withings_sync/sync.py", line 157, in sync_garmin
    garmin.login(ARGS.garmin_username, ARGS.garmin_password)
  File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.6a0-py3.10.egg/withings_sync/garmin.py", line 36, in login
    if hasattr(self.client, "username"):
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.46-py3.10.egg/garth/http.py", line 109, in username
    return self.profile["userName"]
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.46-py3.10.egg/garth/http.py", line 101, in profile
    self._profile = self.connectapi(
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.46-py3.10.egg/garth/http.py", line 171, in connectapi
    resp = self.request(method, "connectapi", path, api=True, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.46-py3.10.egg/garth/http.py", line 129, in request
    self.refresh_oauth2()
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.46-py3.10.egg/garth/http.py", line 168, in refresh_oauth2
    self.oauth2_token = sso.exchange(self.oauth1_token, self)
  File "/usr/local/lib/python3.10/site-packages/garth-0.4.46-py3.10.egg/garth/sso.py", line 146, in exchange
    ).json()
  File "/usr/local/lib/python3.10/site-packages/requests-2.32.3-py3.10.egg/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Moenmann** [comment]
Same problem here. I think it's connected to Garmin  MFA? I'm unable to disable that on my account.

**Comment by luiscachog** [comment]
Same issue here, can't disable the 2FA

**Comment by RobinFlikkema** [comment]
Same here; As far as I know, i do not use 2FA currently; Also not sure where this would be enabled for garmin, as I cannot find settings about it.

It _is_ the Garmin Connect integration. As only outputting to JSON works fine.

```
> 2025-05-22 19:03:39,643 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): thegarth.s3.amazonaws.com:443
> 2025-05-22 19:03:40,106 - urllib3.connectionpool - DEBUG - https://thegarth.s3.amazonaws.com:443 "GET /oauth_consumer.json HTTP/1.1" 200 124
> 2025-05-22 19:03:40,115 - requests_oauthlib.oauth1_auth - DEBUG - Signing request <PreparedRequest [POST]> using client <Client client_key=SOMEGUIDISHERE, client_secret=****, resource_owner_key=SOMEGUIDISHERE, resource_owner_secret=****, signature_method=HMAC-SHA1, signature_type=AUTH_HEADER, callback_uri=None, rsa_key=None, verifier=None, realm=None, encoding=utf-8, decoding=utf-8, nonce=None, timestamp=None>
> 2025-05-22 19:03:40,115 - requests_oauthlib.oauth1_auth - DEBUG - Including body in call to sign: True
> 2025-05-22 19:03:40,115 - oauthlib.oauth1.rfc5849 - DEBUG - Collected params: [('oauth_nonce', 'LOTSOFNUMBERSAREHERE'), ('oauth_timestamp', '1747933420'), ('oauth_version', '1.0'), ('oauth_signature_method', 'HMAC-SHA1'), ('oauth_consumer_key', 'SOMEGUIDISHERE'), ('oauth_token', 'SOMEGUIDISHERE')]
> 2025-05-22 19:03:40,115 - oauthlib.oauth1.rfc5849 - DEBUG - Normalized params: oauth_consumer_key=SOMEGUIDISHERE&oauth_nonce=LOTSOFNUMBERSAREHERE&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1747933420&oauth_token=SOMEGUIDISHERE&oauth_version=1.0
> 2025-05-22 19:03:40,115 - oauthlib.oauth1.rfc5849 - DEBUG - Normalized URI: https://connectapi.garmin.com/oauth-service/oauth/exchange/user/2.0
> 2025-05-22 19:03:40,115 - oauthlib.oauth1.rfc5849 - DEBUG - Signing: signature base string: POST&https%3A%2F%2Fconnectapi.garmin.com%2Foauth-service%2Foauth%2Fexchange%2Fuser%2F2.0&oauth_consumer_key%3SOMEGUIDISHERE%26oauth_nonce%3LOTSOFNUMBERSHERE%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1747933420%26oauth_token%3SOMEGUIDISHERE%26oauth_version%3D1.0
> 2025-05-22 19:03:40,115 - oauthlib.oauth1.rfc5849 - DEBUG - Signature: SOMEBASE64STRING
> 2025-05-22 19:03:40,115 - oauthlib.oauth1.rfc5849 - DEBUG - Encoding URI, headers and body to utf-8.
> 2025-05-22 19:03:40,115 - requests_oauthlib.oauth1_auth - DEBUG - Updated url: https://connectapi.garmin.com/oauth-service/oauth/exchange/user/2.0
> 2025-05-22 19:03:40,115 - requests_oauthlib.oauth1_auth - DEBUG - Updated headers: {b'User-Agent': b'com.garmin.android.apps.connectmobile', b'Accept-Encoding': b'gzip, deflate', b'Accept': b'*/*', b'Connection': b'keep-alive', b'Content-Type': b'application/x-www-form-urlencoded', b'Content-Length': b'0', b'Authorization': b'OAuth oauth_nonce="LOTSOFNUMBERSAREHERE", oauth_timestamp="1747933420", oauth_version="1.0", oauth_signature_method="HMAC-SHA1", oauth_consumer_key="SOMEGUIDISHERE", oauth_token="SOMEGUIDISHERE", oauth_signature="LOTSOFTEXT%3D"'}
> 2025-05-22 19:03:40,115 - requests_oauthlib.oauth1_auth - DEBUG - Updated body: ''
> 2025-05-22 19:03:40,115 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): connectapi.garmin.com:443
> 2025-05-22 19:03:40,440 - urllib3.connectionpool - DEBUG - https://connectapi.garmin.com:443 "POST /oauth-service/oauth/exchange/user/2.0 HTTP/1.1" 401 None
> Traceback (most recent call last):
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\requests\models.py", line 971, in json
>     return complexjson.loads(self.text, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "E:\Projects\WithingsSync\.venv\Scripts\withings-sync.exe\__main__.py", line 7, in <module>
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\withings_sync\sync.py", line 510, in main
>     sync()
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\withings_sync\sync.py", line 469, in sync
>     gar_wg_state = sync_garmin(fit_data_weight)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\withings_sync\sync.py", line 157, in sync_garmin
>     garmin.login(ARGS.garmin_username, ARGS.garmin_password)
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\withings_sync\garmin.py", line 38, in login
>     if hasattr(self.client, "username"):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\garth\http.py", line 109, in username
>     return self.profile["userName"]
>            ^^^^^^^^^^^^
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\garth\http.py", line 101, in profile
>     self._profile = self.connectapi(
>                     ^^^^^^^^^^^^^^^^
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\garth\http.py", line 171, in connectapi
>     resp = self.request(method, "connectapi", path, api=True, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\garth\http.py", line 129, in request
>     self.refresh_oauth2()
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\garth\http.py", line 168, in refresh_oauth2
>     self.oauth2_token = sso.exchange(self.oauth1_token, self)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\garth\sso.py", line 146, in exchange
>     ).json()
>       ^^^^^^
>   File "E:\Projects\WithingsSync\.venv\Lib\site-packages\requests\models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
