### ISSUE TITLE
pip install issue: UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 2494: illegal multibyte sequence

### ISSUE THREAD

**Issue by denven** [jaroslawhartman/withings-sync#170]
Python 3.12
```
PS C:\Users\pcname> pip install withings-sync
Collecting withings-sync
  Using cached withings-sync-4.2.4.tar.gz (22 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\pcname\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\pcname\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pcname\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pcname\AppData\Local\Temp\pip-build-env-ck8t4wzr\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pcname\AppData\Local\Temp\pip-build-env-ck8t4wzr\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\pcname\AppData\Local\Temp\pip-build-env-ck8t4wzr\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\pcname\AppData\Local\Temp\pip-build-env-ck8t4wzr\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
        File "<string>", line 10, in read
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 2494: illegal multibyte sequence
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by ForrestHong** [comment]
I got the same error on window 11 Python 3.12.4


`pip install withings-sync
WARNING: Ignoring invalid distribution ~ (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~heel (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
Collecting withings-sync
  Using cached withings_sync-4.2.7.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\fh935779\AppData\Local\Temp\pip-install-w0tlygnk\withings-sync_9eda79b3567f4ce393903c6ed7e52e1e\setup.py", line 23, in <module>
          long_description=read("README.md"),
                           ^^^^^^^^^^^^^^^^^
        File "C:\Users\dev\AppData\Local\Temp\pip-install-w0tlygnk\withings-sync_9eda79b3567f4ce393903c6ed7e52e1e\setup.py", line 10, in read
          return open(os.path.join(os.path.dirname(__file__), fname)).read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 2494: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`
