### ISSUE TITLE
Can't input token when running in docker

### ISSUE THREAD

**Issue by JeanMichelDeveloper** [jaroslawhartman/withings-sync#172]
When running the script fo the first time in docker, the run is exited with an error when I need to enter the token.

The error is the following :
 
2024-06-29 19:08:22 Traceback (most recent call last):
2024-06-29 19:08:22   File "/usr/local/bin/withings-sync", line 33, in <module>
2024-06-29 19:08:22     sys.exit(load_entry_point('withings-sync==4.2.4', 'console_scripts', 'withings-sync')())
2024-06-29 19:08:22   File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.4-py3.10.egg/withings_sync/sync.py", line 510, in main
2024-06-29 19:08:22     sync()
2024-06-29 19:08:22   File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.4-py3.10.egg/withings_sync/sync.py", line 415, in sync
2024-06-29 19:08:22     withings = WithingsAccount()
2024-06-29 19:08:22   File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.4-py3.10.egg/withings_sync/withings2.py", line 197, in __init__
2024-06-29 19:08:22     self.withings = WithingsOAuth2()
2024-06-29 19:08:22   File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.4-py3.10.egg/withings_sync/withings2.py", line 69, in __init__
2024-06-29 19:08:22     ] = self.get_authenticationcode()
2024-06-29 19:08:22   File "/usr/local/lib/python3.10/site-packages/withings_sync-4.2.4-py3.10.egg/withings_sync/withings2.py", line 118, in get_authenticationcode
2024-06-29 19:08:22     authentification_code = input("Token : ")
2024-06-29 19:08:22 EOFError: EOF when reading a line
2024-06-29 19:08:22 Token :

I have the "Token : " input but I can't give it the token because the run is finished with the error. 

Any idea why ?

**Comment by longstone** [comment]
Please provide the full command. Do you have startet the container with `docker run -it...`?

**Comment by JeanMichelDeveloper** [comment]
I do not use a command line.
This happens when I un the image I downloaded in Docker desktop as shown below:
![image](https://github.com/jaroslawhartman/withings-sync/assets/98649417/10114413-a969-4758-9f44-af3d9851d9e2)
The next screen when running is the console with the logs provided

**Comment by longstone** [comment]
You have to go in interactive mode.
