### ISSUE TITLE
Does not build, weird version error

### ISSUE THREAD

**Issue by marlemion** [jaroslawhartman/withings-sync#185]
git clone 

pyhton setup.py build

Traceback (most recent call last):
  File "/home/eger/withings-sync/setup.py", line 13, in <module>
    setup(
  File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 145, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 333, in __init__
    self.metadata.version = self._normalize_version(self.metadata.version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 369, in _normalize_version
    normalized = str(Version(version))
                     ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: {version!r}")
packaging.version.InvalidVersion: Invalid version: '${VERSION}\n'

cat .VERSION 
${VERSION}

**Comment by longstone** [comment]
This issue should be adressed with the latest release. if you use the script directly from repository, you can also cahnge the version manually. currently is set to `version="1.0.0.dev1",`
