### ISSUE TITLE
No Sync to Garmin after activating ECG and 2FA

### ISSUE THREAD

**Issue by colonel302** [jaroslawhartman/withings-sync#194]
I have a problem to sync since 25.12. with Version 4.2.7. I get this error:

2024-12-27 14:27:21,538 - withings - INFO - Refresh Access Token
2024-12-27 14:27:21,689 - root - INFO - Fetching measurements from 2024-12-25 10:44 to 2024-12-27 23:59
2024-12-27 14:27:21,928 - withings - INFO - Get Measurements
2024-12-27 14:27:22,091 - root - INFO - 2024-12-27 08:06:02 This Withings metric contains no weight data or blood pressure.  Not syncing...
2024-12-27 14:27:22,092 - root - INFO - 2024-12-27 08:06:02 This Withings metric contains no weight data or blood pressure.  Not syncing...
2024-12-27 14:27:22,092 - root - INFO - 2024-12-27 08:06:02 This Withings metric contains no weight data or blood pressure.  Not syncing...
2024-12-27 14:27:22,092 - root - INFO - 2024-12-26 08:03:43 This Withings metric contains no weight data or blood pressure.  Not syncing...
2024-12-27 14:27:22,092 - root - INFO - 2024-12-26 08:03:43 This Withings metric contains no weight data or blood pressure.  Not syncing...
2024-12-27 14:27:22,092 - root - INFO - 2024-12-26 08:03:43 This Withings metric contains no weight data or blood pressure.  Not syncing...
2024-12-27 14:27:22,093 - root - INFO - No TrainerRoad username or a new measurement - skipping sync
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/colonel/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/colonel/.local/lib/python3.12/site-packages/withings_sync/sync.py", line 510, in main
    sync()
  File "/home/colonel/.local/lib/python3.12/site-packages/withings_sync/sync.py", line 469, in sync
    gar_wg_state = sync_garmin(fit_data_weight)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colonel/.local/lib/python3.12/site-packages/withings_sync/sync.py", line 157, in sync_garmin
    garmin.login(ARGS.garmin_username, ARGS.garmin_password)
  File "/home/colonel/.local/lib/python3.12/site-packages/withings_sync/garmin.py", line 38, in login
    if hasattr(self.client, "username"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colonel/.local/lib/python3.12/site-packages/garth/http.py", line 109, in username
    return self.profile["userName"]
           ^^^^^^^^^^^^
  File "/home/colonel/.local/lib/python3.12/site-packages/garth/http.py", line 101, in profile
    self._profile = self.connectapi(
                    ^^^^^^^^^^^^^^^^
  File "/home/colonel/.local/lib/python3.12/site-packages/garth/http.py", line 171, in connectapi
    resp = self.request(method, "connectapi", path, api=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colonel/.local/lib/python3.12/site-packages/garth/http.py", line 129, in request
    self.refresh_oauth2()
  File "/home/colonel/.local/lib/python3.12/site-packages/garth/http.py", line 168, in refresh_oauth2
    self.oauth2_token = sso.exchange(self.oauth1_token, self)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colonel/.local/lib/python3.12/site-packages/garth/sso.py", line 146, in exchange
    ).json()
      ^^^^^^
  File "/usr/lib/python3/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by colonel302** [comment]
BS: Ubuntu 24.04 LTS
Python: 3.12
Withings-Sync: 4.2.7.

**Comment by stynoo** [comment]
Hello, if you are sure the username/password combination is still correct, try upgrading garth.

**Comment by colonel302** [comment]
Hi,
username/password works at the Garmin Connect. How can I upgrade garth?

**Comment by colonel302** [comment]
Good morning,
I think it is a problem with the permanent MFA which was enabled using ECG from Garmin.
Changeing to  credentials via environment variables does not help.

**Comment by stynoo** [comment]
Ah Garmin doing Garming things again...   
So to get what happened correctly...   This didn't suddenly stopped working, you added a new device with ECG functionality and Garmin is required by law to enable MFA/2FA when processing ECG data.  
Garth should work with this, I am not sure why it goes wrong.

**Comment by colonel302** [comment]
It seems so. Any ideas on how to get it working again? I have also deactivated the ECG function again. Unfortunately, I can no longer deactivate the 2FA in the profile. I have written to Garmin support about this.

**Comment by michaelknox** [comment]
I am seeing the same on my side. Again with the ECG function and most likely the 2FA. I'll send them a note as well.

**Comment by colonel302** [comment]
> I had the same problem after activating ECG. I removed the .garmin_session in my homedirectory to re-authenticate to Garmin. This will request a new securitycode. For me it is working again after this.

Thank you so much. This worked for me. After deleting I Was asked for mfa Code and the sync works.
