### ISSUE TITLE
Does anyone else have an issue with Garmin SSO?

### ISSUE THREAD

**Issue by jgrecu** [jaroslawhartman/withings-sync#25]
since yesterday, without any changes the script is not working anymore. I am getting the following error:

2021-05-19 11:08:42,413 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): sso.garmin.com:443
2021-05-19 11:08:42,886 - urllib3.connectionpool - DEBUG - https://sso.garmin.com:443 "GET /sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&clientId=GarminConnect&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&consumeServiceTicket=false HTTP/1.1" 200 None
2021-05-19 11:08:42,963 - urllib3.connectionpool - DEBUG - https://sso.garmin.com:443 "POST /sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&clientId=GarminConnect&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&consumeServiceTicket=false HTTP/1.1" 403 None
Traceback (most recent call last):
  File "/usr/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==3.1.3', 'console_scripts', 'withings-sync')())
  File "/usr/lib/python3.9/site-packages/withings_sync/sync.py", line 196, in main
    sync(**vars(args))
  File "/usr/lib/python3.9/site-packages/withings_sync/sync.py", line 184, in sync
    session = garmin.login(garmin_username, garmin_password)
  File "/usr/lib/python3.9/site-packages/withings_sync/garmin.py", line 156, in login
    session = self._get_session(email=username, password=password)
  File "/usr/lib/python3.9/site-packages/withings_sync/garmin.py", line 93, in _get_session
    raise APIException('SSO error %s %s' % (ssoResp.status_code, ssoResp.text))
withings_sync.garmin.APIException: SSO error 403 <html lang="en-US" class="no-js" xmlns="http://www.w3.org/1999/xhtml">

the script runs as such: 'withings-sync -f 2021-05-01 -v'

**Comment by stynoo** [comment]
Yes, can you test https://github.com/jaroslawhartman/withings-sync/pull/24 ?

**Comment by jgrecu** [comment]
yes, I applied your patch and it works now as expected. 

Thank you very much

**Comment by sfregosi** [comment]
Could you explain how to apply the patch? Is there a new version that should be installed (pip install -U withings-sync...tried this with no success) or another way to apply it? Thank you!
