### ISSUE TITLE
Update to 3.3.0 causes withings auth to fail

### ISSUE THREAD

**Issue by ossgeek314** [jaroslawhartman/withings-sync#35]
After upgrading the docker image to the latest v3.3.0 release.  I get an error code 2554 from withings reported on the command line.  Here is the output I get when starting the docker
```
docker start -i withings
2021-06-04 11:39:48,502 - withings - ERROR - Can't read config file /root/.withings_user.json
2021-06-04 11:39:48,502 - withings - WARNING - User interaction needed to get Authentification Code from Withings!
2021-06-04 11:39:48,502 - withings - WARNING - 
2021-06-04 11:39:48,502 - withings - WARNING - Open the following URL in your web browser and copy back the token. You will have *30 seconds* before the token expires. HURRY UP!
2021-06-04 11:39:48,502 - withings - WARNING - (This is one-time activity)
2021-06-04 11:39:48,502 - withings - WARNING - 
2021-06-04 11:39:48,502 - withings - INFO - https://account.withings.com/oauth2_user/authorize2?response_type=code&client_id=183e03e1f363110b3551f96765c98c10e8f1aa647a37067a1cb64bbbaf491626&state=OK&scope=user.metrics&redirect_uri=https://jaroslawhartman.github.io/withings-sync/contrib/withings.html&
2021-06-04 11:39:48,503 - withings - INFO - 
Token : <copied_token_pasted_here>
2021-06-04 11:40:04,791 - withings - INFO - Get Access Token
2021-06-04 11:40:05,113 - withings - ERROR - Received error code: 2554
2021-06-04 11:40:05,113 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2021-06-04 11:40:05,113 - withings - ERROR - 
2021-06-04 11:40:05,114 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==3.3.0', 'console_scripts', 'withings-sync')())
  File "/usr/local/lib/python3.9/site-packages/withings_sync-3.3.0-py3.9.egg/withings_sync/sync.py", line 196, in main
    sync(**vars(args))
  File "/usr/local/lib/python3.9/site-packages/withings_sync-3.3.0-py3.9.egg/withings_sync/sync.py", line 78, in sync
    withings = WithingsAccount()
  File "/usr/local/lib/python3.9/site-packages/withings_sync-3.3.0-py3.9.egg/withings_sync/withings2.py", line 162, in __init__
    self.withings = WithingsOAuth2()
  File "/usr/local/lib/python3.9/site-packages/withings_sync-3.3.0-py3.9.egg/withings_sync/withings2.py", line 66, in __init__
    self.getAccessToken()
  File "/usr/local/lib/python3.9/site-packages/withings_sync-3.3.0-py3.9.egg/withings_sync/withings2.py", line 127, in getAccessToken
    self.user_config['access_token'] = body.get('access_token')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by MartinCa** [comment]
I have experienced the same issue here, but I was unsure it was something on my end causing issues.

**Comment by ossgeek314** [comment]
There was definitely a change made to the withings2.py code to prepare for a switchover by withings to a new auth style mentioned in ticket #34  
I wonder if withings isn't ready for this switch yet on all accounts (wild guess)

**Comment by stv0g** [comment]
Thats strange. Error 2554 stands for "Not implemented".

I dont get why they return this error.

**Comment by MartinCa** [comment]
I tested the python version with this commit: https://github.com/jaroslawhartman/withings-sync/commit/9153773e4e2ad32ce05f4d2a87c6eb9e8ed80ae2 and it works with Withings so it does seem like the following commit breaks something currently: https://github.com/jaroslawhartman/withings-sync/commit/4b1298a8124b9c74dda4feafc4c82881b7615e7d

**Comment by stynoo** [comment]
Can you try https://github.com/jaroslawhartman/withings-sync/pull/36 plz?

**Comment by ossgeek314** [comment]
> Can you try #36 plz?

I can confirm this patch results in a working sync.  Thanks!

**Comment by gilabrantes** [comment]
@stynoo That patch also fixed the problem for me. Thanks!

**Comment by stv0g** [comment]
#36 has been merged. Version v0.3.1 is also released.

**Comment by MartinCa** [comment]
> #36 has been merged. Version v0.3.1 is also released.

Should this not have been v3.3.1?

**Comment by stv0g** [comment]
Sorry my fault. I fixed the versioning

**Comment by jpfy** [comment]
I am getting this error using the docker arm 3.2.0 release.  Is there a docker version for a pi which resolves this issue?
