### ISSUE TITLE
401 errors even with 24hr interval.

### ISSUE THREAD

**Issue by JanJoh** [jaroslawhartman/withings-sync#40]
Hello!

So, I've upgraded to latest version. But i still hit the following even with 24hr between attempts. 

GARMIN_USERNAME and GARMIN_PASSOWRD are set via env variables.

`j2@pentserv02:~/withings-sync$ withings-sync -f 2021-01-01
2021-07-06 07:29:04,446 - withings - INFO - Refresh Access Token
2021-07-06 07:29:04,865 - withings - INFO - Get Measurements
2021-07-06 07:29:05,117 - root - INFO - This Withings metric contains no weight data.  Not syncing...
2021-07-06 07:29:05,123 - root - INFO - No Trainerroad username or a new measurement - skipping sync
Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 11, in <module>
    load_entry_point('withings-sync==3.3.1', 'console_scripts', 'withings-sync')()
  File "/usr/local/lib/python3.6/dist-packages/withings_sync-3.3.1-py3.6.egg/withings_sync/sync.py", line 196, in main
    sync(**vars(args))
  File "/usr/local/lib/python3.6/dist-packages/withings_sync-3.3.1-py3.6.egg/withings_sync/sync.py", line 184, in sync
    session = garmin.login(garmin_username, garmin_password)
  File "/usr/local/lib/python3.6/dist-packages/withings_sync-3.3.1-py3.6.egg/withings_sync/garmin.py", line 156, in login
    session = self._get_session(email=username, password=password)
  File "/usr/local/lib/python3.6/dist-packages/withings_sync-3.3.1-py3.6.egg/withings_sync/garmin.py", line 93, in _get_session
    raise APIException('SSO error %s %s' % (ssoResp.status_code, ssoResp.text))
withings_sync.garmin.APIException: SSO error 401 <!DOCTYPE html>
<html lang="en" class="no-js">
    <head>
        <script charset='UTF-8' type="68039df611f8766c1020259a-text/javascript">
            window['adrum-start-time'] = new Date().getTime();
            (function(config){
                config.appKey = 'AD-AAB-AAM-PWF';
                config.adrumExtUrlHttp = 'http://cdn.appdynamics.com';
                config.adrumExtUrlHttps = 'https://cdn.appdynamics.com';
                config.beaconUrlHttp = 'http://col.eum-appdynamics.com';
                config.beaconUrlHttps = 'https://col.eum-appdynamics.com';
                config.xd = {enable : false};
            })(window['adrum-config'] || (window['adrum-config'] = {}));
        </script>

        <script src="//cdn.appdynamics.com/adrum/adrum-latest.js" type="68039df611f8766c1020259a-text/javascript"></script>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge;" />
        <title>GARMIN Authentication Application</title>
        <link href="/sso/css/GAuth.css?20210406" rel="stylesheet" type="text/css" media="all" />

	    <link rel="stylesheet" href=""/>

        <script type="68039df611f8766c1020259a-text/javascript" src="/sso/js/jquery/3.1.1/jquery.min.js?20210319"></script>
        <script type="68039df611f8766c1020259a-text/javascript">jQuery.noConflict();</script>
		<script type="68039df611f8766c1020259a-text/javascript" src="/sso/js/jquery-validate/1.16.0/jquery.validate.min.js?20210319"></script>
        <script type="68039df611f8766c1020259a-text/javascript" src="/sso/js/jsUtils.js?20210406"></script>
        <script type="68039df611f8766c1020259a-text/javascript" src="/sso/js/json2.js"></script>
        <script type="68039df611f8766c1020259a-text/javascript" src="/sso/js/consoleUtils.js?20210319"></script>
        <script type="68039df611f8766c1020259a-text/javascript" src="/sso/js/postmessage.js?20210319"></script>
        <script type="68039df611f8766c1020259a-text/javascript" src="/sso/js/popupWindow.js"></script>
        <script type="68039df611f8766c1020259a-text/javascript" src="/sso/js/base.js?20210406"></script>
		<script type="68039df611f8766c1020259a-text/javascript" src="/sso/js/gigyaUtils.js?20210319"></script>
        <script type="68039df611f8766c1020259a-text/javascript" src="/sso/js/login.js?20210319"></script>
        <script type="68039df611f8766c1020259a-text/javascript">
            var parent_url      = "";
            var status 			= "FAIL";
			var result          = "error";
			var clientId		= 'GarminConnect';
			var embedWidget 	= false;
			var isUsernameDefined = (true == true) || (true == true);

            // Gigya callback to SocialSignInController for brand new social network users redirects to this page
            // to popup Create or Link Social Account page, but has a possibly mangled source parameter
            // where "?" is set as "<QM>", so translate it back to "?" here.
            parent_url = parent_url.replace('<QM>', '?');
            var parent_scheme   = parent_url.substring(0, parent_url.indexOf("://"));
            var parent_hostname = parent_url.substring(parent_scheme.length + 3, parent_url.length);
            if (parent_hostname.indexOf("/") != -1) {
                parent_hostname = parent_hostname.substring(0, parent_hostname.indexOf("/"));
            }
            var parentHost      	   = parent_scheme + "://" + parent_hostname;
			var createAccountConfigURL = '\/createNewAccount?service%3Dhttps%253A%252F%252Fconnect.garmin.com%252Fmodern%26clientId%3DGarminConnect%26gauthHost%3Dhttps%253A%252F%252Fsso.garmin.com%252Fsso%26consumeServiceTicket%3Dfalse';
            var socialConfigURL        = 'https://sso.garmin.com/sso/socialSignIn?service%3Dhttps%3A%2F%2Fconnect.garmin.com%2Fmodern%26clientId%3DGarminConnect%26gauthHost%3Dhttps%3A%2F%2Fsso.garmin.com%2Fsso%26consumeServiceTicket%3Dfalse';
            var gigyaURL               = "https://cdns.gigya.com/js/gigya.js?apiKey=2_R3ZGY8Bqlwwk3_63knoD9wA_m-Y19mAgW61bF_s5k9gymYnMEAtMrJiF5MjF-U7B";

            if (createAccountConfigURL.indexOf('%253A%252F%252F') != -1) {
            	createAccountConfigURL = decodeURIComponent(createAccountConfigURL);
            }
            consoleInfo('signin.html embedWidget: false, createAccountConfigURL: \/createNewAccount?service%3Dhttps%253A%252F%252Fconnect.garmin.com%252Fmodern%26clientId%3DGarminConnect%26gauthHost%3Dhttps%253A%252F%252Fsso.garmin.com%252Fsso%26consumeServiceTicket%3Dfalse, socialEnabled: true, gigyaSupported: true, socialConfigURL(): https://sso.garmin.com/sso/socialSignIn?service%3Dhttps%3A%2F%2Fconnect.garmin.com%2Fmodern%26clientId%3DGarminConnect%26gauthHost%3Dhttps%3A%2F%2Fsso.garmin.com%2Fsso%26consumeServiceTicket%3Dfalse');

            if (socialConfigURL.indexOf('%3A%2F%2F') != -1) {
            	socialConfigURL = decodeURIComponent(socialConfigURL);
            }

            if( status != null && status != ''){
            	send({'status':status});
            }

            jQuery(document).ready( function(){

                consoleInfo("signin.html: setting field validation rules...");

                jQuery("#username").rules("add",{
                    required: true,
                    messages: {
                        required:  "Email is required."
                }});

                jQuery("#password").rules("add", {
                    required: true,
                    messages: {
                        required:  "Password is required."
                    }
                });

                consoleInfo("signin.html: done setting field validation rules...");

            });

            XD.receiveMessage(function(m){
                consoleInfo("signin.html: " + m.data + " received on " + window.location.host);
                 if (m && m.data) {
                     var md = m.data;
                     if (typeof(md) === 'string') {
                         md = JSON.parse(m.data);
                     }
                     if (md.setUsername) {
                         consoleInfo("signin.html: Setting username \"" + md.username + "\"...");
                         jQuery("#signInWithDiffLink").click(); // Ensure the normal login form is shown.
                         jQuery("#username").val(md.username);
                         jQuery("#password").focus();
                     }
                 }
             }, parentHost);
        </script>
    </head>
    <body>

        
        <div id="GAuth-component">
            
            <div id="login-component" class="blueForm-basic">
               <input type="hidden" id="queryString" value="service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&amp;clientId=GarminConnect&amp;gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&amp;consumeServiceTicket=false" />
	     	   <input type="hidden" id="contextPath" value="/sso" />
                
                <div id="login-state-default">
                    <h2>Sign In</h2>

                    <form method="post" id="login-form">

                        <div class="form-alert">

                            <div id="status" class="error">Invalid sign in. (Passwords are case sensitive.)</div>

                            <div id="username-error" style="display:none;"></div>
                            <div id="password-error" style="display:none;"></div>
                        </div>
                        <div class="textfield">
							<label for="username">Email</label>
                           		

								
							    <input class="login_email" name="username" id="username" value="j2@mupp.net" type="email" spellcheck="false" autocorrect="off" autocapitalize="off"/>

                        </div>

                        <div class="textfield">
                            <label for="password">Password</label>
                            <a id="loginforgotpassword" class="login-forgot-password" style="cursor:pointer">(Forgot?)</a>
                            <input type="password" name="password" id="password" spellcheck="false" autocorrect="off" autocapitalize="off" />
                             <strong id="capslock-warning" class="information" title="Caps lock is on." style="display: none;">Caps lock is on.</strong>
					    </div>
                        <input type="hidden" name="embed" value="false"/>
                        <input type="hidden" name="_csrf" value="2F64E8AD909DF7C93482C27BFED95F29664D6A217E3F1EAA596A5A9E271E092D8840C8EC1643133D6AD030CB55DACAC2D3FA" />
                        <button type="submit" id="login-btn-signin" class="btn1" accesskey="l">Sign In</button>

                        

                    </form>
                </div>
                

                
	            <div id="login-create-account">

	            </div>
	            

	            
	            <div id="SSI-component">

	            </div>
	            
                <div class="clearfix"></div> 
            </div>
            

		</div>
		

        <script type="68039df611f8766c1020259a-text/javascript">
            jQuery(document).ready(function(){
            	resizePageOnLoad(jQuery("#GAuth-component").height());

		        if(isUsernameDefined == true){
		            // If the user's login just failed, redisplay the email/username specified, and focus them in the password field.
		            jQuery("#password").focus();
		        } else if(false == true && result != "PASSWORD_RESET_RESULT"){
                    // Otherwise focus them in the username field of the login dialog.
                    jQuery("#username").focus();
                }

                // Scroll to top of iframe to fix problem where Firefox 3.0-3.6 browsers initially show top of iframe cutoff.
                location.href="#";

                if(!embedWidget){
                	jQuery('.createAccountLink').click(function(){
	                    send({'openLiteBox':'createAccountLink', 'popupUrl': createAccountConfigURL, 'popupTitle':'Create An Account', 'clientId':clientId});
	                });
                }
            });
        </script>
    <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="68039df611f8766c1020259a-|49" defer=""></script></body>
</html>`

**Comment by greykapp1001** [comment]
First off thanks for the work, was keen to get this installed and up and running. 

It worked the very first time when running the command. No issues. Was sure not to run it again. The next time I ran it was about 12 hours later and got the 403 error. Every day for the last week, got the 403 error. What is worse, is that now I cannot log into the Garmin Connect App on my phone, with the same public IP as the (home) computer that gets the 403.

I have to switch the phone off the home network onto 4G for garmin connect log in to work :( - clearly something is not right with the cloudflare part of the sign on.

**Comment by Schischu** [comment]
Hi @JanJoh I had the same problem.
I recommend to you to double check if the env for the password has indeed really been set correctly.
For me it seems the special characters in the password caused the issue.
You can check after setting them with the command 'set'.

Make sure that if you set your password to use ' to no have special characters like $ wrongly interpreted.
GARMIN_PASSWORD='abcdefg$123'

**Comment by misiektoja** [comment]
For me it worked only once, during initial sync. Now if I want to resync I get 403 every day, however long I wait between resyncs. So it stopped working for me completely. I tried different IPs, no luck. I'm using Mac OS X.

**Comment by greykapp1001** [comment]
thanks @misiektoja and @Schischu ... I have been quite intrigued by your solutions. I had used the cmd variables - the last two weeks have been on and off but off for me - I would say with once every 6 hours, 403 about 75% of the time or more.

I just ran using the env variables for both username and password instead (and confirmed with ' and checked with echo) - and nope, still 403 on the first attempt. i will leave it to run and see what happens these coming days...

**Comment by nanderson** [comment]
I don't know if this was the actual solution but I think upgrading openssl was the solution for me. I did some research on the CloudFlare generated 403 errors and found that some of them were a result of the version of openssl that was being used to negotiate the SSL connection to Garmin. I was struggling with intermittent 403s running withings-sync on a CentOS 7.9 box with openssl 1.0.2k-21.el7_9.x86_64. When I moved the app to a RPi running Raspbian with openssl 1.1.1d-0+deb10u7 the problem completely disappeared.

**Comment by mcia1** [comment]
Same errors for me. Doing some Google research revealed that this CloudFlare error 403 can be circumvented by using HTTP/2 to query the website. I adjusted the code and now it works for me. I created a pull request to integrate my changes: https://github.com/jaroslawhartman/withings-sync/pull/49

**Comment by greykapp1001** [comment]
hi @ciancim this works a charm now. Many thanks!!
