### ISSUE TITLE
AccessToken Issue

### ISSUE THREAD

**Issue by jmegie** [jaroslawhartman/withings-sync#41]
This started happening this morning:

$ withings-sync -v
2021-07-13 14:24:40,298 - withings - INFO - Get Access Token
2021-07-13 14:24:40,309 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2021-07-13 14:24:40,713 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /v2/oauth2 HTTP/1.1" 200 63
2021-07-13 14:24:40,715 - withings - ERROR - Received error code: 503
2021-07-13 14:24:40,715 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2021-07-13 14:24:40,715 - withings - ERROR - 
2021-07-13 14:24:40,715 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
2021-07-13 14:24:40,716 - withings - INFO - Refresh Access Token
2021-07-13 14:24:40,717 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2021-07-13 14:24:41,096 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /v2/oauth2 HTTP/1.1" 200 64
2021-07-13 14:24:41,098 - withings - ERROR - Received error code: 503
2021-07-13 14:24:41,098 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2021-07-13 14:24:41,098 - withings - ERROR - 
2021-07-13 14:24:41,098 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/withings_sync/sync.py", line 196, in main
    sync(**vars(args))
  File "/usr/local/lib/python3.9/site-packages/withings_sync/sync.py", line 78, in sync
    withings = WithingsAccount()
  File "/usr/local/lib/python3.9/site-packages/withings_sync/withings2.py", line 164, in __init__
    self.withings = WithingsOAuth2()
  File "/usr/local/lib/python3.9/site-packages/withings_sync/withings2.py", line 68, in __init__
    self.refreshAccessToken()
  File "/usr/local/lib/python3.9/site-packages/withings_sync/withings2.py", line 157, in refreshAccessToken
    self.user_config['access_token'] = body.get('access_token')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by jmegie** [comment]
I deleted ~/.withings_user.json, and obtained a new token, but it was still failing. I ended up creating my own callback URL, getting my own client ID/secret, and refreshed the token - this seems to have done the trick. I'm not sure if there's a problem with your Client ID/Secret, or if it was a caching problem on my end.

**Comment by kpd001** [comment]
Having the same issue since ~1 week ago. Have tried obtaining a new token and no luck. Seems I'll have to try getting my own client ID unless there is a simpler fix around

**Comment by jmegie** [comment]
It's something on withings side. I've had to refresh my own token twice now. It's almost as if they're expiring the tokens randomly.

**Comment by mwhrtin** [comment]
Happening to me as well using the provided Withings application. I had to refresh the token this morning and a second time a few hours later.

**Comment by jmegie** [comment]
I have not had any issues since my second token refresh. Will continue to monitor.

**Comment by matustraco** [comment]
Hi all. I have the same problem and I have been trying to solve it myself, but was not even closely successful. I have been getting this message for months:

2021-12-02 00:36:09,906 - withings - INFO - Get Access Token
2021-12-02 00:36:10,204 - withings - ERROR - Received error code: 503
2021-12-02 00:36:10,204 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2021-12-02 00:36:10,205 - withings - ERROR -
2021-12-02 00:36:10,206 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
2021-12-02 00:36:10,206 - withings - INFO - Refresh Access Token
2021-12-02 00:36:10,392 - withings - ERROR - Received error code: 503
2021-12-02 00:36:10,392 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2021-12-02 00:36:10,393 - withings - ERROR -
2021-12-02 00:36:10,394 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
Traceback (most recent call last):
File "/usr/local/bin/withings-sync", line 33, in <module>
sys.exit(load_entry_point('withings-sync==3.3.1', 'console_scripts', 'withings-sync')())
File "/usr/local/lib/python3.9/site-packages/withings_sync-3.3.1-py3.9.egg/withings_sync/sync.py", line 196, in main
sync(**vars(args))
File "/usr/local/lib/python3.9/site-packages/withings_sync-3.3.1-py3.9.egg/withings_sync/sync.py", line 78, in sync
withings = WithingsAccount()
File "/usr/local/lib/python3.9/site-packages/withings_sync-3.3.1-py3.9.egg/withings_sync/withings2.py", line 164, in __init__
self.withings = WithingsOAuth2()
File "/usr/local/lib/python3.9/site-packages/withings_sync-3.3.1-py3.9.egg/withings_sync/withings2.py", line 68, in __init__
self.refreshAccessToken()
File "/usr/local/lib/python3.9/site-packages/withings_sync-3.3.1-py3.9.egg/withings_sync/withings2.py", line 157, in refreshAccessToken
self.user_config['access_token'] = body.get('access_token')
AttributeError: 'NoneType' object has no attribute 'get'

Nothing was helping. Today I was able to somehow disconnect the app from Withings on their account.withings.com/parter page and after that I was able to trash everything and pull the docker image anew. As it started automaticaly I have seen in the logs of the container that it went to the app registration/authentication process with those 30s wait time for pasting the code... since the window with logs is not interactive I could not enter the code. And since then it throws the same message as mentioned above.
Can someone please help me with it?

Thanks very much

**Comment by longstone** [comment]
The Issue is from pre-fixing Auth issues. And for a week there was no activity. So I going to close this one. Feel free to reopen if the error persits.

**Comment by csab77** [comment]
Ran into this exact crash (`AttributeError: 'NoneType' object has no attribute 'get'` in `refresh_accesstoken()`) five years later, still unfixed. Opened #259 with a fix: both `get_accesstoken()` and `refresh_accesstoken()` now go through a helper that raises a proper `WithingsException` on any non-zero API status instead of falling through to overwrite (and then have `__init__` persist) `access_token`/`refresh_token`/`userid` with `None`.

Root cause turned out to be a dead/rotated refresh token (Withings status 503 = "Invalid Params: invalid refresh_token", not an HTTP error), so the underlying trigger here is likely the same as what caused the original report — this PR doesn't prevent that from happening, but it stops it from turning into permanent, unrecoverable corruption of `.withings_user.json` requiring a full re-authorization, which is what happened both in the original report and in my own case.
