### ISSUE TITLE
Login Garmin and 2FA

### ISSUE THREAD

**Issue by daniel3** [jaroslawhartman/withings-sync#43]
When I try to run the sync with 2FA on, I get the following error message. Is works flawlessly when I turn 2FA off. Is it possible to implement 2FA so I can run the sync with 2FA on?

2021-11-17 18:43:41,505 - withings - INFO - Refresh Access Token
2021-11-17 18:43:41,931 - withings - INFO - Get Measurements
2021-11-17 18:43:42,137 - root - INFO - No Trainerroad username or a new measurement - skipping sync
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Daniel\AppData\Roaming\Python\Python310\Scripts\withings-sync.exe\__main__.py", line 7, in <module>
  File "C:\Users\Daniel\AppData\Roaming\Python\Python310\site-packages\withings_sync\sync.py", line 196, in main
    sync(**vars(args))
  File "C:\Users\Daniel\AppData\Roaming\Python\Python310\site-packages\withings_sync\sync.py", line 184, in sync
    session = garmin.login(garmin_username, garmin_password)
  File "C:\Users\Daniel\AppData\Roaming\Python\Python310\site-packages\withings_sync\garmin.py", line 156, in login
    session = self._get_session(email=username, password=password)
  File "C:\Users\Daniel\AppData\Roaming\Python\Python310\site-packages\withings_sync\garmin.py", line 93, in _get_session
    raise APIException('SSO error %s %s' % (ssoResp.status_code, ssoResp.text))
withings_sync.garmin.APIException: SSO error 302

**Comment by longstone** [comment]
I think this issue would be resolved by switching to OAuth, see also https://github.com/jaroslawhartman/withings-sync/issues/3.

**Comment by LsVzqz** [comment]
I'm also having this issue, in case someone figures out how to solve around the email/2FA code sent.

**Comment by pentafive** [comment]
Garmin updated the firmware on my watch to support their EKG app. If you use that app it will force 2FA saying "Permanent two-step verification has been enabled." Even if you uninstall the EKG app, you won't be able to turn off 2FA.

Right now I'm using manual workaround from @LsVzqz (Thanks!) however it's not ideal.

**Comment by radu-solomon** [comment]
Same issue here. @LsVzqz thanks for the suggestion. Using that manually for now.

**Comment by midzelis** [comment]
Oh man - mandatory 2FA seems a bit much! At least they are emailing the code, which means you can automate it. Just need to add another script that automatically logs in to your email server (using IMAP/POP3) and looks for the code. 

Is it possible to register your own 2FA generator? If so, then its even easier - the TOPT generators are really simple as well. The only time this becomes a real problem is if they start requiring their own proprietary to send you a push notification. You wouldn't be able to intercept that.

**Comment by Cloud9Developer** [comment]
Just seeing this thread. I, too, have been plagued by the "Permanent MFA" due to the ECG app. Any quick/easy workarounds for this?

**Comment by pentafive** [comment]
> Just seeing this thread. I, too, have been plagued by the "Permanent MFA" due to the ECG app. Any quick/easy workarounds for this? (I'm currently doing the manual export/import in garmin connect)

Not that I've seen. This will require changes to code for sure. I've been manually downloading the .fit file and uploading to connect manually.

**Comment by Cloud9Developer** [comment]
> > Just seeing this thread. I, too, have been plagued by the "Permanent MFA" due to the ECG app. Any quick/easy workarounds for this? (I'm currently doing the manual export/import in garmin connect)
> 
> Not that I've seen. This will require changes to code for sure. I've been manually downloading the .fit file and uploading to connect manually.

Same. Was hoping there was a workaround since I would rather it be automated lol. I may try to fork the project and fix it (If I can). Haven't done much in the way of MFA before, but we'll see (If I can find the time lol)

**Comment by stynoo** [comment]
It looks like [this project](https://github.com/philosowaffle/peloton-to-garmin) has Garmin MFA support figured out.

**Comment by Cloud9Developer** [comment]
Gonna take a look at that then! May take a while to understand how it works, but thanks for the lead!

**Comment by Cloud9Developer** [comment]
It's a bit clunky, but it works :)

https://github.com/Cloud9Developer/withings-garmin-mfa

**Comment by matin** [comment]
Garth migration solved this

**Comment by LsVzqz** [comment]
> Garth migration solved this

How do I use the garth migration? Is that a different project?

**Comment by matin** [comment]
It's already migrated. Upgrade to the latest version

**Comment by Cloud9Developer** [comment]
I see the update. When you get the auth token, it doesn't have an expiration ever? I'm asking because I am setting this up to use cron and would like to basically forget about it

**Comment by matin** [comment]
The expiration of the MFA token (part of the session token) is one year.

**Comment by AlmightyCZ** [comment]
Since yesterday, I’ve been receiving the MFA code request every time I run the sync. When I checked the oauth1_token.json file, I noticed that the expiration timestamp is now almost equal to the time of the sync. For example, this morning, the mfa_expiration_timestamp was "2025-11-27T06:26:29".

Additionally, I observed that the MFA prompt changed from "Enter MFA code" to "MFA code:".

Has something changed on Garmin’s side, or could it be related to the MFA library?
