### ISSUE TITLE
Error Code 503

### ISSUE THREAD

**Issue by dominoto** [jaroslawhartman/withings-sync#46]
Hello! Trying to run the script on my dietPi, I get this:

> 2021-12-21 21:41:24,057 - withings - INFO - Get Access Token
> 2021-12-21 21:41:24,359 - withings - ERROR - Received error code: 503
> 2021-12-21 21:41:24,359 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
> 2021-12-21 21:41:24,359 - withings - ERROR - 
> 2021-12-21 21:41:24,359 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
> 2021-12-21 21:41:24,360 - withings - INFO - Refresh Access Token
> 2021-12-21 21:41:24,549 - withings - ERROR - Received error code: 503
> 2021-12-21 21:41:24,550 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
> 2021-12-21 21:41:24,550 - withings - ERROR - 
> 2021-12-21 21:41:24,550 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
> Traceback (most recent call last):
>   File "/usr/local/bin/withings-sync", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/dist-packages/withings_sync/sync.py", line 196, in main
>     sync(**vars(args))
>   File "/usr/local/lib/python3.7/dist-packages/withings_sync/sync.py", line 78, in sync
>     withings = WithingsAccount()
>   File "/usr/local/lib/python3.7/dist-packages/withings_sync/withings2.py", line 164, in __init__
>     self.withings = WithingsOAuth2()
>   File "/usr/local/lib/python3.7/dist-packages/withings_sync/withings2.py", line 68, in __init__
>     self.refreshAccessToken()
>   File "/usr/local/lib/python3.7/dist-packages/withings_sync/withings2.py", line 157, in refreshAccessToken
>     self.user_config['access_token'] = body.get('access_token')
> AttributeError: 'NoneType' object has no attribute 'get'

**Comment by ErikBergfurInfor** [comment]
This is what you get when the .withings_user.json is too old or invalid.

1. Rename or delete .withings_user.json
2. Run withings-sync
3. Complete the oauth-token process

**Comment by eribr** [comment]
This is what you get when the .withings_user.json is too old or invalid.

1. Rename or delete .withings_user.json
2. Run withings-sync
3. Complete the oauth-token process

**Comment by starcat13** [comment]
@eribrI have the same issue. After I delete .withings_user.json it ask to get token again and works once.
But next time it shows error 601:
2022-02-02 08:42:37,273 - withings - INFO - Refresh Access Token
2022-02-02 08:42:37,589 - withings - ERROR - Received error code: 601
2022-02-02 08:42:37,589 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2022-02-02 08:42:37,589 - withings - ERROR -
2022-02-02 08:42:37,589 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
2022-02-02 08:42:37,911 - withings - INFO - Get Measurements

and next time error 503 again:
2022-02-02 08:42:42,535 - withings - INFO - Get Access Token
2022-02-02 08:42:42,902 - withings - ERROR - Received error code: 503
2022-02-02 08:42:42,902 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2022-02-02 08:42:42,902 - withings - ERROR -
2022-02-02 08:42:42,902 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
2022-02-02 08:42:42,902 - withings - INFO - Refresh Access Token
2022-02-02 08:42:43,221 - withings - ERROR - Received error code: 503
2022-02-02 08:42:43,221 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2022-02-02 08:42:43,221 - withings - ERROR -
2022-02-02 08:42:43,221 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
Traceback (most recent call last):
  File "/home/starcat/.local/bin/withings-sync", line 8, in <module>
    sys.exit(main())
  File "/home/starcat/.local/lib/python3.8/site-packages/withings_sync/sync.py", line 196, in main
    sync(**vars(args))
  File "/home/starcat/.local/lib/python3.8/site-packages/withings_sync/sync.py", line 78, in sync
    withings = WithingsAccount()
  File "/home/starcat/.local/lib/python3.8/site-packages/withings_sync/withings2.py", line 164, in __init__
    self.withings = WithingsOAuth2()
  File "/home/starcat/.local/lib/python3.8/site-packages/withings_sync/withings2.py", line 68, in __init__
    self.refreshAccessToken()
  File "/home/starcat/.local/lib/python3.8/site-packages/withings_sync/withings2.py", line 157, in refreshAccessToken
    self.user_config['access_token'] = body.get('access_token')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by dominoto** [comment]
> 

I deleted .withings_user.json and did the authentication again. I still got error "Unable to retrieve Garmin username!", so I relogged into Garmin Connect through the website and it seems to be working for now. Thanks!
