### ISSUE TITLE
Withings 503 errors

### ISSUE THREAD

**Issue by matthewnessworthy** [jaroslawhartman/withings-sync#53]
Same error whether i use my garmin username+password or not

`withings-sync -v`
```
2022-03-03 15:22:26,073 - root - DEBUG - Script invoked with the following arguments: Namespace(garmin_username=None, garmin_password=None, trainerroad_username=None, trainerroad_password=None, fromdate=datetime.date(2022, 3, 3), todate=datetime.date(2022, 3, 3), csv_weight_dir=None, no_upload=False, verbose=True)
2022-03-03 15:22:26,073 - withings - INFO - Get Access Token
2022-03-03 15:22:26,079 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2022-03-03 15:22:26,289 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /v2/oauth2 HTTP/1.1" 200 63
2022-03-03 15:22:26,290 - withings - ERROR - Received error code: 503
2022-03-03 15:22:26,290 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2022-03-03 15:22:26,290 - withings - ERROR -
2022-03-03 15:22:26,290 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
2022-03-03 15:22:26,291 - withings - INFO - Refresh Access Token
2022-03-03 15:22:26,294 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2022-03-03 15:22:26,488 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /v2/oauth2 HTTP/1.1" 200 64
2022-03-03 15:22:26,490 - withings - ERROR - Received error code: 503
2022-03-03 15:22:26,490 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2022-03-03 15:22:26,490 - withings - ERROR -
2022-03-03 15:22:26,490 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
Traceback (most recent call last):
  File "/Users/matthew/.pyenv/versions/3.10.0/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==3.3.1', 'console_scripts', 'withings-sync')())
  File "/Users/matthew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/withings_sync/sync.py", line 338, in main
    sync()
  File "/Users/matthew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/withings_sync/sync.py", line 262, in sync
    withings = WithingsAccount()
  File "/Users/matthew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/withings_sync/withings2.py", line 184, in __init__
    self.withings = WithingsOAuth2()
  File "/Users/matthew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/withings_sync/withings2.py", line 72, in __init__
    self.refresh_accesstoken()
  File "/Users/matthew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/withings_sync/withings2.py", line 175, in refresh_accesstoken
    self.user_config["access_token"] = body.get("access_token")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by patrickbs96** [comment]
I had the same problem just now, try deleting the file `.withings_user.json` in your home path and redo the authorization process. It worked for me after that

**Comment by matthewnessworthy** [comment]
@patrickbs96 didn't help, also tried uninstalling and reinstalling `withings-sync` as well

**Comment by darrencope** [comment]
> I had the same problem just now, try deleting the file `.withings_user.json` in your home path and redo the authorization process. It worked for me after that

This worked for me just now. Thanks!

**Comment by matthewnessworthy** [comment]
@patrickbs96 
Ah, sorry, i thought you were referring to credentials file inside the `withings-sync` lib files
`rm ~/.withings_user.json` worked correctly for me
Thanks!
