### ISSUE TITLE
Can't access Withings data unless run as root

### ISSUE THREAD

**Issue by dougbert-b** [jaroslawhartman/withings-sync#81]
When run as root, the program (installed directly from the github repository) accesses the Withings data OK,
but it fails when run normally.  Could this be caused by a permission problem on some file?  I assume the "503" error code
is a HTTP error, not a Withings-specific code.

```
blackbox:/home/doug>sudo withings-sync -f 2022-9-17
2022-09-27 11:44:11,980 - withings - INFO - Refresh Access Token
2022-09-27 11:44:12,398 - root - INFO - Fetching measurements from 2022-09-17 04:00 to 2022-09-28 03:59
2022-09-27 11:44:12,806 - withings - INFO - Get Measurements
2022-09-27 11:44:13,231 - root - INFO - No Trainerroad username or a new measurement - skipping sync
2022-09-27 11:44:13,231 - root - INFO - No Garmin username - skipping sync
blackbox:/home/doug>
blackbox:/home/doug>
blackbox:/home/doug>withings-sync -f 2022-9-17
2022-09-27 11:44:19,504 - withings - INFO - Get Access Token
2022-09-27 11:44:19,891 - withings - ERROR - Received error code: 503
2022-09-27 11:44:19,891 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2022-09-27 11:44:19,891 - withings - ERROR - 
2022-09-27 11:44:19,891 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
2022-09-27 11:44:19,892 - withings - INFO - Refresh Access Token
2022-09-27 11:44:20,246 - withings - ERROR - Received error code: 503
2022-09-27 11:44:20,246 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2022-09-27 11:44:20,247 - withings - ERROR - 
2022-09-27 11:44:20,247 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 11, in <module>
    load_entry_point('withings-sync==3.4.2', 'console_scripts', 'withings-sync')()
  File "/usr/local/lib/python3.8/dist-packages/withings_sync-3.4.2-py3.8.egg/withings_sync/sync.py", line 396, in main
    sync()
  File "/usr/local/lib/python3.8/dist-packages/withings_sync-3.4.2-py3.8.egg/withings_sync/sync.py", line 323, in sync
    withings = WithingsAccount()
  File "/usr/local/lib/python3.8/dist-packages/withings_sync-3.4.2-py3.8.egg/withings_sync/withings2.py", line 189, in __init__
    self.withings = WithingsOAuth2()
  File "/usr/local/lib/python3.8/dist-packages/withings_sync-3.4.2-py3.8.egg/withings_sync/withings2.py", line 73, in __init__
    self.refresh_accesstoken()
  File "/usr/local/lib/python3.8/dist-packages/withings_sync-3.4.2-py3.8.egg/withings_sync/withings2.py", line 180, in refresh_accesstoken
    self.user_config["access_token"] = body.get("access_token")
AttributeError: 'NoneType' object has no attribute 'get'
blackbox:/home/doug>
```

**Comment by stynoo** [comment]
It seems you ran the script as root the first time, so it generated the .withings_user.json file as root in the root home folder.  
Running the script as a normal user afterwards doesn't magically grant the normal user access to root owned files in the root home folder.

To get you started again, run it as a normal user (without extra parameters) and follow the instructions as you did the first time you launched the script.

**Comment by dougbert-b** [comment]
Thanks!  I deleted the root and my own .withings_user.json files, and it works now.

I can successfully transfer a couple of week's worth of weight data to Garmin Connect, but if I try to transfer a couple of year's worth, it times out after several seconds with a bunch of Python messages, starting with:

```
2022-09-28 21:23:09,862 - garmin - INFO - Garmin Connect User Name: doug@dougbraun.com
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
  File "/usr/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

```

Is there a known upper bound on the number of readings that can be transferred in one shot?  
Is it possible to increase the timeout value?

Doug

**Comment by dougbert-b** [comment]
Despite the timeout, Garmin apparently received and processed all the weight data.
Also, I discovered how to adjust the timeout in the httpx APIs.
