### ISSUE TITLE
Compatible Python version?

### ISSUE THREAD

**Issue by Aekschen** [jaroslawhartman/withings-sync#90]
I'm having trouble getting a match for the python version and this project. I had it running in the past but I'm with a fresh python install.

Status:
Python 3.11.0 can't install lxml anymore
Python 3.7.9 has a type issue or gets no results
```
2022-11-11 21:31:25,917 - withings - INFO - Refresh Access Token
2022-11-11 21:31:26,141 - root - INFO - Fetching measurements from 2021-12-31 23:00 to 2022-11-11 22:59
2022-11-11 21:31:26,388 - withings - INFO - Get Measurements
Traceback (most recent call last):
  File "E:\data\dev\Python\withings\.venv\Scripts\withings-sync-script.py", line 11, in <module>
    load_entry_point('withings-sync==3.4.2', 'console_scripts', 'withings-sync')()
  File "e:\data\dev\python\withings\.venv\lib\site-packages\withings_sync\sync.py", line 396, in main
    sync()
  File "e:\data\dev\python\withings\.venv\lib\site-packages\withings_sync\sync.py", line 349, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "e:\data\dev\python\withings\.venv\lib\site-packages\withings_sync\sync.py", line 248, in prepare_syncdata
    groupdata["weight"] / pow(groupdata["height"], 2), 1
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

Am I the only one having problems like this?
Maybe I had it running with Python 3.1 or similar?

**Comment by stynoo** [comment]
It should be compatible with .7 .8 .9 iirc.   Your error is most likely solved with updating the script.  (see https://github.com/jaroslawhartman/withings-sync/releases/tag/v3.4.4)

**Comment by Aekschen** [comment]
> 

Thanks! I will check installing directly from git. I assume pip is not serving the latest version with the fix you are referring to.

**Comment by Aekschen** [comment]
Installing with Python 3.7.9 and 
`pip install git+https://github.com/jaroslawhartman/withings-sync.git@master` turned out successful 👍
