### ISSUE TITLE
Unable to Sync: unsupported operand type(s) for /: 'NoneType' and 'float' 

### ISSUE THREAD

**Issue by henne49** [jaroslawhartman/withings-sync#91]
Still getting an error when I try to sync my data. I have found entries, that this should be fixe, but I still receive the error

docker run -v $HOME:/root --interactive --tty --name withings ghcr.io/jaroslawhartman/withings-sync:master --garmin-username=XXXX --garmin-password=YYYYY -f 2022-07-28
2022-11-23 11:47:27,425 - withings - INFO - Refresh Access Token
2022-11-23 11:47:27,615 - root - INFO - Fetching measurements from 2022-07-28 00:00 to 2022-11-23 23:59
2022-11-23 11:47:27,854 - withings - INFO - Get Measurements
Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==3.5', 'console_scripts', 'withings-sync')())
  File "/root/.local/lib/python3.10/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/root/.local/lib/python3.10/site-packages/withings_sync/sync.py", line 349, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/root/.local/lib/python3.10/site-packages/withings_sync/sync.py", line 248, in prepare_syncdata
    groupdata["weight"] / pow(groupdata["height"], 2), 1
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

**Comment by henne49** [comment]
How can I check this? I'm using the docker image? withings ghcr.io/jaroslawhartman/withings-sync:master

**Comment by stynoo** [comment]
Ah, I see that the 'latest' image tag is from 4 months ago.  Is this something you can kick @longstone ? 
Maybe using the 'master' or 'nightly' tag would be a workaround for now?

**Comment by henne49** [comment]
But I'm using master, see my docker command. ghcr.io/jaroslawhartman/withings-sync:master

**Comment by stynoo** [comment]
Ah my bad.  Then it's not a valid workaround :-)  Let's see if someone with more docker-fu can chime in on this...

**Comment by henne49** [comment]
I also tried to use the python script, but got the same error, I installed with pip. Where can I get the latest script from, then I will try that as well.

Von: stynoo ***@***.***>
Datum: Mittwoch, 23. November 2022 um 13:37
An: jaroslawhartman/withings-sync ***@***.***>
Cc: henne49 ***@***.***>, Author ***@***.***>
Betreff: Re: [jaroslawhartman/withings-sync] Unable to Sync: unsupported operand type(s) for /: 'NoneType' and 'float' (Issue #91)

Ah my bad. Then it's not a valid workaround :-) Let's see if someone with more docker-fu can chime in on this...

**Comment by henne49** [comment]
If I do that, I only have files like these:
fit.py  garmin.py  sync.py  trainerroad.py  withings2.py

I have now idea how to use, there is no withings-sync to use

**Comment by henne49** [comment]
got that working
