### ISSUE TITLE
Error configuring script

### ISSUE THREAD

**Issue by cameronsenese** [jaroslawhartman/withings-sync#94]
Hi, I'm following the instructions in README to configure the script.
Am successfully generating Withings token and providing back to the script when prompted. Error as follows:

```
docker run -v $HOME:/root --interactive --tty --name withings ghcr.io/jaroslawhartman/withings-sync:master --garmin-username=<USERNAME> --garmin-password=<PASS>

2023-01-05 01:29:49,878 - withings - ERROR - Can't read config file /root/.withings_user.json
2023-01-05 01:29:49,878 - withings - WARNING - User interaction needed to get Authentification Code from Withings!
2023-01-05 01:29:49,878 - withings - WARNING -
2023-01-05 01:29:49,878 - withings - WARNING - Open the following URL in your web browser and copy back the token. You will have *30 seconds* before the token expires. HURRY UP!
2023-01-05 01:29:49,878 - withings - WARNING - (This is one-time activity)
2023-01-05 01:29:49,878 - withings - WARNING -
2023-01-05 01:29:49,878 - withings - INFO - https://account.withings.com/oauth2_user/authorize2?response_type=code&client_id=183e03e1f363110b3551f96765c98c10e8f1aa647a37067a1cb64bbbaf491626&state=OK&scope=user.metrics&redirect_uri=https://jaroslawhartman.github.io/withings-sync/contrib/withings.html&
2023-01-05 01:29:49,878 - withings - INFO -
Token : <TOKEN>                                                                                                                                                                
2023-01-05 01:30:26,885 - withings - INFO - Get Access Token
2023-01-05 01:30:28,411 - withings - ERROR - Received error code: 503
2023-01-05 01:30:28,411 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2023-01-05 01:30:28,411 - withings - ERROR -
2023-01-05 01:30:28,411 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
2023-01-05 01:30:28,411 - withings - INFO - Refresh Access Token
2023-01-05 01:30:29,273 - withings - ERROR - Received error code: 503
2023-01-05 01:30:29,273 - withings - ERROR - Check here for an interpretation of this error: http://developer.withings.com/api-reference#section/Response-status
2023-01-05 01:30:29,273 - withings - ERROR -
2023-01-05 01:30:29,273 - withings - ERROR - If it's regarding an invalid code, try to start the script again to obtain a new link.
Traceback (most recent call last):
  File "/usr/local/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==3.5.1', 'console_scripts', 'withings-sync')())
  File "/usr/local/lib/python3.10/site-packages/withings_sync-3.5.1-py3.10.egg/withings_sync/sync.py", line 396, in main
    sync()
  File "/usr/local/lib/python3.10/site-packages/withings_sync-3.5.1-py3.10.egg/withings_sync/sync.py", line 323, in sync
    withings = WithingsAccount()
  File "/usr/local/lib/python3.10/site-packages/withings_sync-3.5.1-py3.10.egg/withings_sync/withings2.py", line 189, in __init__
    self.withings = WithingsOAuth2()
  File "/usr/local/lib/python3.10/site-packages/withings_sync-3.5.1-py3.10.egg/withings_sync/withings2.py", line 73, in __init__
    self.refresh_accesstoken()
  File "/usr/local/lib/python3.10/site-packages/withings_sync-3.5.1-py3.10.egg/withings_sync/withings2.py", line 180, in refresh_accesstoken
    self.user_config["access_token"] = body.get("access_token")
AttributeError: 'NoneType' object has no attribute 'get'
```

Any guidance appreciated please!

**Comment by timmhayes** [comment]
I updated to 3.5.1 ([just published](https://github.com/jaroslawhartman/withings-sync/issues/88)) and am getting the same 503 error. The only difference is that I already have the generated `.withings_user.json `config file on my system and do not see the first few errors and warnings you get (under the 2023-01-05 01:29:49,878  timecode).

**Comment by cameronsenese** [comment]
Note: file /root/.withings_user.json is not created during script execution.

**Comment by timmhayes** [comment]
> Note: file /root/.withings_user.json is not created during script execution.

That file was generated for me when I followed the README and ran `withings-sync -f 2019-01-25 -v`, but that was using the previous version I installed via pip.

**Comment by laurent-antoine** [comment]
I am having the code 503 error too
After several minutes I get a message in the terminal ending with this :
self.user_config["access_token"] = body.get("access_token")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by romain-charpie** [comment]
Hello,
Any news on that issue? 
I just made a fresh install today and get the exact same error code 503.

**Comment by myplatox** [comment]
Same error here.
Runs on a python 3.9.2 with latest withings-sync 3.6.1 on debian11 in a venv.
(Runs fine on windows 10 with python 3.8.2 also with lateset v3.6.1)

Any news or help?

**Comment by marksdale** [comment]
I've been experiencing the same issue.  Nothing I have tired has made a difference.  Everything up to current version.  

Any suggestions please?

**Comment by marksdale** [comment]
Fixed my issue by replacing the $HOME env value with a name for the volume.  I used 'withings'.  It created the volume as expected and wrote the withings_user.json file to it.  I'm no Docker expert and don't know why the original stopped working, but hope this may help someone.

**Comment by longstone** [comment]
seems like setting a valid $HOME resolved this issue. thanks for sharing!
