### ISSUE TITLE
Sync not working when using a Withings blood pressure monitor on the same day

### ISSUE THREAD

**Issue by kbeilix** [jaroslawhartman/withings-sync#98]
Hello,

I am runnning the script an Alpine container and it works mostly great. Thanks for all the work that was put into this.
I experienced that on some days the script fails to sync the data and I traced it down to days where Ialso use my Withings blood pressure monitor. Running the script in debug mode on this day yield these outputs (I replaced logins and strings that had seemed like a Token by XXXXXX).

I have some Python experience but not enough to fix this myself. Please let me know if can assist in fixing this.

[log1.txt](https://github.com/jaroslawhartman/withings-sync/files/10503649/log1.txt)
[log2.log](https://github.com/jaroslawhartman/withings-sync/files/10503650/log2.log)

**Comment by stynoo** [comment]
I had a quick look at this on my phone.  It looks like it has something to do with the commented out code block on line 240 in sync.py.
```
       # if groupdata["weight"] is None:
            # logging.info(
            #    "This Withings metric contains no weight data.  Not syncing..."
            # )
            # logging.debug("Detected data: ")
            # continue
```
A quick fix would probably reactivating this, but as Garmin is rolling out Blood Pressure stats as we speak, we surely want to be able to process and upload them in the future as well.

**Comment by kbeilix** [comment]
Just gave this a try. I uncommented the lines in sync.py and indeed the error changes but sync is still not running through:

console:


```
Traceback (most recent call last):
  File "/usr/bin/withings-sync", line 33, in <module>
    sys.exit(load_entry_point('withings-sync==3.5.1', 'console_scripts', 'withings-sync')())
  File "/usr/lib/python3.10/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/usr/lib/python3.10/site-packages/withings_sync/sync.py", line 345, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/usr/lib/python3.10/site-packages/withings_sync/sync.py", line 288, in prepare_syncdata
    last_date_time = groupdata["date_time"]
KeyError: 'date_time'
```

the redirected output of the command gives now:
```
2023-01-26 19:30:18,009 - root - DEBUG - Script invoked with the following arguments: Namespace(garmin_username='XXXXXXXXXXXXX', garmin_password='XXXXXXXXX', trainerroad_username='', trainerroad_password='', fromdate=datetime.datetime(2023, 1, 24, 0, 0), todate=datetime.datetime(2023, 1, 24, 0, 0), to_fit=False, to_json=False, output=None, no_upload=False, verbose=True)
2023-01-26 19:30:18,010 - withings - INFO - Refresh Access Token
2023-01-26 19:30:18,012 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2023-01-26 19:30:18,673 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /v2/oauth2 HTTP/1.1" 200 219
2023-01-26 19:30:18,675 - root - INFO - Fetching measurements from 2023-01-24 00:00 to 2023-01-24 23:59
2023-01-26 19:30:18,676 - withings - DEBUG - Get Height
2023-01-26 19:30:18,677 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2023-01-26 19:30:20,007 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /measure?action=getmeas HTTP/1.1" 200 None
2023-01-26 19:30:20,532 - withings - DEBUG - Height received
2023-01-26 19:30:20,539 - withings - INFO - Get Measurements
2023-01-26 19:30:20,540 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wbsapi.withings.net:443
2023-01-26 19:30:21,165 - urllib3.connectionpool - DEBUG - https://wbsapi.withings.net:443 "POST /measure?action=getmeas HTTP/1.1" 200 1066
2023-01-26 19:30:21,167 - withings - DEBUG - Measurements received
2023-01-26 19:30:21,167 - root - INFO - This Withings metric contains no weight data.  Not syncing...
2023-01-26 19:30:21,167 - root - DEBUG - Detected data: 
2023-01-26 19:30:21,167 - root - DEBUG - 2023-01-24 05:28:36 Detected data: 
2023-01-26 19:30:21,167 - root - DEBUG - Weight: 81.57600000000001 kg
2023-01-26 19:30:21,168 - root - DEBUG - Fat Mass Weight: 16.2 kg
2023-01-26 19:30:21,168 - root - DEBUG - Muscle Mass: 62.11 kg
2023-01-26 19:30:21,168 - root - DEBUG - Hydration: 43.97 kg
2023-01-26 19:30:21,168 - root - DEBUG - Bone Mass: 3.25 kg
2023-01-26 19:30:21,168 - root - DEBUG - Fat Ratio: 19.859 %
2023-01-26 19:30:21,168 - root - DEBUG - Fat Free Mass: 65.376 kg
2023-01-26 19:30:21,168 - root - DEBUG - Record: 2023-01-24 05:28:36, height=1.83 m, weight=81.58 kg, fat_ratio=19.86 %, muscle_mass=62.11 kg, percent_hydration=53.9 %, bone_mass=3.25 kg, bmi=24.4
2023-01-26 19:30:21,168 - root - DEBUG - Processed data:
```

**Comment by longstone** [comment]
I'm currently not able to code or test, but it seems to have an issue with this code.
Can you try it like this:

```
        if groupdata["weight"] is None:
            logging.info(
               "This Withings metric contains no weight data.  Not syncing..."
            )
            logging.debug("Detected data: ", group)
            del syncDict[dt]
            continue
```

This adds also the logging of the full group entry as is.

**Comment by kbeilix** [comment]
I modified the sync.py accordingly. Unfortunalty it does not seem to work (see attached log file)
[log5.log](https://github.com/jaroslawhartman/withings-sync/files/10539277/log5.log)

**Comment by kbeilix** [comment]
Just gave the update code in the pull request a try. No further error messages but the weigth data is still not recognized:

```
2023-01-31 20:26:53,038 - withings - DEBUG - Measurements received
2023-01-31 20:26:53,038 - root - INFO - 2023-01-20 06:15:39 This Withings metric contains no weight data.  Not syncing...
2023-01-31 20:26:53,039 - root - DEBUG - Diastolic Blood Pressure: 77 mmHg
2023-01-31 20:26:53,039 - root - DEBUG - Systolic Blood Pressure: 116 mmHg
2023-01-31 20:26:53,039 - root - DEBUG - Heart Pulse: 56 bpm
2023-01-31 20:26:53,039 - root - DEBUG - 2023-01-20 05:46:03 Detected data: 
2023-01-31 20:26:53,039 - root - DEBUG - Weight: 82.141 kg
2023-01-31 20:26:53,039 - root - DEBUG - Fat Mass Weight: 16.62 kg
2023-01-31 20:26:53,039 - root - DEBUG - Muscle Mass: 62.25 kg
2023-01-31 20:26:53,039 - root - DEBUG - Hydration: 44.07 kg
2023-01-31 20:26:53,039 - root - DEBUG - Bone Mass: 3.2600000000000002 kg
2023-01-31 20:26:53,039 - root - DEBUG - Fat Ratio: 20.234 %
2023-01-31 20:26:53,039 - root - DEBUG - Fat Free Mass: 65.521 kg
2023-01-31 20:26:53,039 - root - DEBUG - Record: 2023-01-20 05:46:03, height=1.83 m, weight=82.14 kg, fat_ratio=20.23 %, muscle_mass=62.25 kg, percent_hydration=53.65 %, bone_mass=3.26 kg, bmi=24.5
2023-01-31 20:26:53,039 - root - INFO - 2023-01-19 05:58:17 This Withings metric contains no weight data.  Not syncing...
2023-01-31 20:26:53,039 - root - DEBUG - Diastolic Blood Pressure: 76 mmHg
2023-01-31 20:26:53,040 - root - DEBUG - Systolic Blood Pressure: 119 mmHg
2023-01-31 20:26:53,040 - root - DEBUG - Heart Pulse: 60 bpm
2023-01-31 20:26:53,040 - root - DEBUG - 2023-01-19 05:23:58 Detected data: 
2023-01-31 20:26:53,040 - root - DEBUG - Weight: 81.988 kg
2023-01-31 20:26:53,040 - root - DEBUG - Fat Mass Weight: 17.07 kg
2023-01-31 20:26:53,040 - root - DEBUG - Muscle Mass: 61.68 kg
2023-01-31 20:26:53,040 - root - DEBUG - Hydration: 43.58 kg
2023-01-31 20:26:53,040 - root - DEBUG - Bone Mass: 3.22 kg
2023-01-31 20:26:53,040 - root - DEBUG - Fat Ratio: 20.82 %
2023-01-31 20:26:53,040 - root - DEBUG - Fat Free Mass: 64.918 kg
2023-01-31 20:26:53,040 - root - DEBUG - Record: 2023-01-19 05:23:58, height=1.83 m, weight=81.99 kg, fat_ratio=20.82 %, muscle_mass=61.68 kg, percent_hydration=53.15 %, bone_mass=3.22 kg, bmi=24.5
2023-01-31 20:26:53,040 - root - INFO - 2023-01-18 21:55:01 This Withings metric contains no weight data.  Not syncing...
2023-01-31 20:26:53,040 - root - DEBUG - Diastolic Blood Pressure: 81 mmHg
2023-01-31 20:26:53,041 - root - DEBUG - Systolic Blood Pressure: 121 mmHg
```

**Comment by longstone** [comment]
Could you dump it to json and check if there are entries for weight? On my side, with the code from the pr, it looked good.

**Comment by longstone** [comment]
Tested, it successfully updated and created the weight entries in garmin connect

```
2023-02-01 12:05:14,260 - withings - INFO - Refresh Access Token
2023-02-01 12:05:14,558 - root - INFO - Fetching measurements from 2023-01-30 08:01 to 2023-02-01 22:59
2023-02-01 12:05:14,951 - withings - INFO - Get Measurements
2023-02-01 12:05:15,233 - root - INFO - 2023-01-31 20:36:42 This Withings metric contains no weight data.  Not syncing...
2023-02-01 12:05:15,233 - root - INFO - 2023-01-31 07:18:48 This Withings metric contains no weight data.  Not syncing...
2023-02-01 12:05:15,234 - root - INFO - 2023-01-30 21:47:19 This Withings metric contains no weight data.  Not syncing...
2023-02-01 12:05:15,236 - root - INFO - No Trainerroad username or a new measurement - skipping sync
2023-02-01 12:05:19,617 - garmin - INFO - Garmin Connect User Name: <snip>
2023-02-01 12:05:19,916 - root - INFO - Fit file uploaded to Garmin Connect
2023-02-01 12:05:19,916 - withings - INFO - Saving Last Sync
```

**Comment by kbeilix** [comment]
My appologies. I just tried to create a json file and it transfers the data like you expected. Repeatedd that for 3 different days and the data pops up at Garmin and no error message anymore. I cannot reproduce the failure from 2 days ago ahown above.
So it really seems to be resolved. Thanks for you quick help @longstone
